### DISCUSSION TITLE
Configuration naming scheme

### DISCUSSION THREAD

**Discussion by matchai** [starship/starship#117] [General]
Before we reach v1.0.0, I would like to review and iron out the configuration naming scheme.

Here is an example of a valid configuration file:
```toml
[character]
symbol = "❯"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
added = "➕"
renamed = "👅"
deleted = "🗑"

[package]
disabled = true
```

# Discussion points

- Should we have all segments that are the visual indicator for the module (e.g. "⬢" in `nodejs`) be called {module}_symbol?
	- What about the various status indicators in `git_status`?

- What do we want configuration to look like for prompt-wide values?
	For example, `add_newline` (#116):
	```toml
	# Root-level for prompt-wide values
	add_newline = false
	
	# A separate config object for prompt-wide values
	[prompt]
	add_newline = false
	```

- What do we think about how the disabled state for configuration alternating between requiring a `true` and `false` value?
	For example:
	```toml
	# In this case, `false` disables adding a newline
	add_newline = false 
	
	[line_break]
	# Here, `true` disables the module
	disabled = true	
	```

This is a forum for discussing anything that bothers you about the way configuration is headed, and for pitching solutions to the concerns raised. 🙂

**Comment by pseudo-su** [comment]
I found it somewhat odd that `line_break.disabled` and `add_newline` were not in the same section. As a user they seem related, even if it's not the case

Just spitballing, these could be the equivalent of the current defaults:
```toml
[prompt]
prefix_newline = true
cursor_newline = true # probably not the best name 🤔 (input_newline maybe)
```
or
```toml
[prompt_prefix]
prefix_newline = true

[input_prefix] # (the equivalent of the "character" module)
prefix_newline = true
symbol = "❯"
color_using_status = true
```

**Comment by tiffafoo** [comment]
>Should we have all segments that are the visual indicator for the module (e.g. "⬢" in nodejs) be called {module}_symbol?

I think having a convention that all symbols have a `_symbol` suffix makes sense. 

>What about the various status indicators in git_status?

It would still fit here as you can do `untracked_symbol` for example so 👍 from me.

>What do we want the configuration to look like for prompt-wide values?
For example, add_newline (#116):

IMO I would go for 
```toml
[root] 
# In this case, `false` disables adding a newline
add_newline = false 
 
[line_break]
# Here, `true` disables the module
disabled = true	

```

But we'd have to make sure the name makes it clear that it is a cross-segment configuration. We could also keep it the way you suggested, it should still be clear as long as the documentation reflects it.

>What do we think about how the disabled state for configuration alternating between requiring a true and false value?

I like it! The standards I've seen elsewhere that could be relevant are`off`, `disabled`/`enabled`, which may make it clearer, readability wise.

```toml
# In this case, `false` disables adding a newline
add_newline = "disabled" 
 
[line_break]
# Here, `true` disables the module
show = "disabled"
```

This makes it a lot easier for people to mess up their configuration via typos and personally, I like the minimalism of `true/false` and keeping the `disabled` key which is very clear.

**Comment by brianlow** [comment]
I've found `disabled: true` a little awkward. `true` has a positive connotation but a negative outcome (hidden).

Suggest
```
enabled: true
```
or @sirMerr's suggestion
```
show: enabled/disabled
show: shown/hidden
visibility: visible/hidden (from css)
```

**Comment by brianlow** [comment]
I like how the recent refactoring config now supports
```toml
[git_status]
conflicted = "?"
```
and
```toml
[git_status]
conflicted.value = "?"
conflicted.style = "red"
```
Though I might rename `value` to `symbol`.

Given this I might suggest not suffixing with `_symbol`
```toml
[battery]
full = "🔋"
charging = "⚡️"
discharging.symbol = "x"
discharging.style = "bright-red"
```
