### DISCUSSION TITLE
Looking for example of custom module

### DISCUSSION THREAD

**Discussion by marekkon** [starship/starship#1193] [General]
Hi,
can someone show me some (preferably complicated) example of custom module configuration?

I tried to use custom module to create functionality similar to #1192. I did it like this:
```
[custom.dirty]
command = "echo '*'"  # I want to show asterisk next to branch name
symbol = "*"          # I don't know which works command or symbol
when = "git-changes"  # bash script (function) execution (don't know if I should use """)
style = "fg:red"
```
but it doesn't work. Actually even example from documentation doesn't work, that's why I'd really like to see some working example.

Another idea I have about a custom module is to display the name `VIRTUAL_ENV`, at least until this function is added to the python module.

**Comment by matchai** [comment]
Hey @marekkon 👋

It looks to me like what you're doing should work.
I added the following config and it was working as expected:
```toml
[custom.dirty]
command = "echo '*'"
when = "true"           # Returns a `0` status code
style = "fg:red"
shell = "bash"
```

To make sure the custom module is running as expected, you can run it using the logger environment variable:
```sh
RUST_LOG=starship starship prompt
```
