### DISCUSSION TITLE
How to remove the space after `username`?

### DISCUSSION THREAD

**Discussion by bennyyip** [starship/starship#1268] [General]
My `~/.config/starship.toml`:
```toml
prompt_order = ["username", "custom.ip"]

[username]
suffix = "" # no effect

[custom.ip]
command = """echo 127.0.0.1"""
when = "true"
symbol="@"
prefix = ""
```

The corresponding prompt:
![image](https://user-images.githubusercontent.com/7467687/83112533-df7bfd80-a0f8-11ea-9658-bb7386631160.png)

My question is how to remove the space between `username` and `custom.ip`?
