### DISCUSSION TITLE
How to change prefix color?

### DISCUSSION THREAD

**Discussion by ahmedkhalf** [starship/starship#1342] [General]
I have this is my configuration file:
```TOML
[cmd_duration]
prefix = " "  # This is a clock icon
```
I want it to have the same color as my style `bold yellow`.
How can I change the color of this specific prefix?
