### DISCUSSION TITLE
How to add custom prompts based on script output.

### DISCUSSION THREAD

**Discussion by seivan** [starship/starship#1505] [Q&A] [answered]
Like how would I convert something like this from `Powerlevel10k` to Starship?

```zsh
function prompt_secrets() {
  if [[ -n "$SESSION_SECRETS" ]]; then
    p10k segment -f 3 -t "🔒"
  fi
}
```

I assume it's supposed to be documented under [custom-commands](https://starship.rs/config/#custom-commands) 
But I am not sure how to exactly work that in like the [Powerlevel10k documentation](https://github.com/romkatv/powerlevel10k#extensible) shows

**Comment by matchai** [comment, marked as answer]
This would be the equivalent configuration to add to `~/.config/starship.toml`:
```toml
[custom.secrets]
command = "echo 🔒"  # shows output of command
when = """ [[ -n "$SESSION_SECRETS" ]] """
style = "bold yellow"
```

The new `custom.secrets` module only shows `🔒` when `$SESSION_SECRETS` is not empty.
