### DISCUSSION TITLE
Fonts are a mess: Troubleshooting Wiki

### DISCUSSION THREAD

**Discussion by chipbuster** [starship/starship#1600] [General]
We've had a steady trickle of issues with emojis and powerline symbols not being visible for just about as long as I can remember. There's a pretty simple explanation for this: Unicode is a mess, and fonts aren't that much better.

While we already have [an FAQ entry](https://starship.rs/faq/#why-don-t-i-see-a-glyph-symbol-in-my-prompt) on this subject, it turns out that, depending on several factors, the steps there are still not sufficient to get emoji to render in a terminal. I figured that instead of cluttering up the FAQ with lots of extra instructions per-platform, it'd be better to have an outstanding thread where users can share what configurations worked for them, or any additional insight/discoveries about how fonts are selected on various systems.

If you're posting a font solution, please also post the OS/distro and version you obtained the results on!

**Comment by chipbuster** [comment]
Post your contributions below!

**Comment by chipbuster** [comment]
On pop_OS 20.04 (an Ubuntu 20.04 derivative), I had to do the following:

- Install an emoji font: I chose `fonts-emojione`
- Edit `~/.config/fontconfig/fonts.conf` by adding the following lines:
```
    <match target="pattern">
        <test qual="any" name="family"><string>monospace</string></test>
        <edit name="family" mode="append" binding="weak"><string>EmojiOne</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>serif</string></test>
        <edit name="family" mode="append" binding="weak"><string>EmojiOne</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>sans-serif</string></test>
        <edit name="family" mode="append" binding="weak"><string>EmojiOne</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>emoji</string></test>
        <edit name="family" mode="append" binding="weak"><string>EmojiOne</string></edit>
    </match>
```
replacing `EmojiOne ` with the name of your chosen emoji font.

In case your fontconfig is empty, an example of a full fontconfig can be found at https://github.com/AndydeCleyre/dotfiles/blob/master/.config/fontconfig/fonts.conf

I did not need to reboot, re-login, or run any commands afterwards. Simply closing and reopening the terminal application (Konsole) caused emojis to display correctly.

**Comment by CBenoit** [comment]
On Archlinux (using zsh),

If you don't get the snake by sending
```bash
$ echo -e "\xf0\x9f\x90\x8d"
```
Install `noto-fonts-emoji`

For icons just install a nerd fond as specified in documentation. If using alacritty, one needs to change the `family` value in `bold` category.
For instance:
```yml
# ~/.config/alacritty/alacritty.yml
font:
  normal:
    family: Source Code Pro

  bold:
    family: Fira Code Nerd Font # mostly for cool icons in prompt
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  size: 12.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true
```
Is enough.

![image](https://user-images.githubusercontent.com/3809077/97210867-93f77980-1794-11eb-97ca-d7842af596a6.png)

**Reply by mickimnet** [reply]
That settings only works with the default Starship configuration, as all modules use the bold face.

**Reply by jmvalenciz** [reply]
Thanks. It also works for zsh, fish and bash using kitty terminal

**Reply by TornaxO7** [reply]
Hm... my green arrow still seems to be wrong. I installed the `ttf-firacode-nerd` and the `noto-fonts-emoji` packages. I'm using `alacritty` as well and have the following (font-)config:

<details>

```yml
font:
  normal:
      family: Fira Code Nerd Font
      # family: FiraCode
      #family: Source Code Pro Semibold
      style: Regular

  bold:
      family: Fira Code Nerd Font
      style: Bold

  italic:
      family: Fira Code Nerd Font
      style: Italic

  bold_italic:
      family: Fira Code Nerd Font
      style: Bold,Italic

  size: 12.0
```

</details>

How my prompt currently looks like:

<details>

![image](https://user-images.githubusercontent.com/50843046/222955171-16302811-edbc-417e-ab87-d31f28e7768c.png)

</details>

Do you have an idea what I'm doing wrong?
