### DISCUSSION TITLE
Is there a way to disable one module if another module is "active"?

### DISCUSSION THREAD

**Discussion by maximousblk** [starship/starship#1638] [Q&A] [answered]
I have a custom module to shows [Deno](https://deno.land) version if there is a deno project in the current directory

so i want NodeJS module to be disabled in that directory.

is there currently a way to do this?

module:

```toml
[custom.deno]
command = "deno -V"
files = ["mod.ts", "deps.ts", "mod.js", "deps.js"]
when = """ deno -V """
prefix = "🦕 "
```

**Comment by tommywalkie** [comment, marked as answer]
@maximousblk The `detect_extensions` option in `nodejs` is the culprit. Turn it off.
```toml
[nodejs]
# detect_extensions = ["js", "mjs", "cjs", "ts"]
detect_extensions = []
```
