### DISCUSSION TITLE
How I can show the exit code of the last executed command in my custom module?

### DISCUSSION THREAD

**Discussion by yunielrc** [starship/starship#1639] [Q&A]
I want to show the exit code of the last executed command if it failed:

Something like this:
![Screenshot from 2020-09-02 16-05-17](https://user-images.githubusercontent.com/28462092/92031151-23a11e80-ed36-11ea-9161-cc07b04893c8.png)

My custom module (doesn't work):
![Screenshot from 2020-09-02 16-01-56](https://user-images.githubusercontent.com/28462092/92030963-cb6a1c80-ed35-11ea-8940-fb9601f656ea.png)

Does starship provides an environment variable with the exit code of the last executed command?

For example:
![Screenshot from 2020-09-02 16-07-04](https://user-images.githubusercontent.com/28462092/92031328-6f53c800-ed36-11ea-9bd1-aa2172b21035.png)

@chipbuster

**Comment by yunielrc** [comment]
I found the solution:

![Screenshot from 2020-09-02 17-52-31](https://user-images.githubusercontent.com/28462092/92040904-34a55c00-ed45-11ea-8357-dc4abab220f4.png)

![Screenshot from 2020-09-02 17-52-50](https://user-images.githubusercontent.com/28462092/92040912-37a04c80-ed45-11ea-9f2d-e9d4ad884319.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28462092/92042128-8818a980-ed47-11ea-8f82-be9082b6a8a0.gif)

@chipbuster

**Reply by jankatins** [reply]
Just leave that here for c&p of the next person who wants to do that (with the current master version of starship -> `format` instead of prefix/suffix):

```toml
[custom.exit_status]
description = "The last commands exit status"
command = "echo ${STATUS}"
when = """ [ ${STATUS} -ne 0 ] """
style = "bold red"
format = "[\\[$output\\]]($style) "
```

and the `export STATUS` before (?) the `eval $(starship init zsh)` line.
