### DISCUSSION TITLE
Disabling Modules in 0.45.2

### DISCUSSION THREAD

**Discussion by drewauff** [starship/starship#1752] [Q&A] [answered]
Im on MacOS Catalina using iTerm2..

Cannot disable modules.

The only documentation I could find for this new verison suggests

`<module>.disabled`

this does nothing.

any ideas?

**Comment by andytom** [comment, marked as answer]
To disable a module you would set the `disabled` option to `true` in the Starship config file.

For example to disable the [Java module](https://starship.rs/config/#java) you would add the following
```toml
# ~/.config/starship.toml

[java]
disabled = true
```

There is also a handy CLI shortcut that you can use to do the same thing: `starship configure java.disabled true`.

**Reply by drewauff** [reply]
I figured it out my fault..

while have you here.

how do I make the word "took" the same color as the duration color?

**Reply by davidkna** [reply]
try this:
```toml
# ~/.config/starship.toml

[cmd_duration]
# default is "took [$duration]($style) "
format = "[took $duration]($style) "
```
