### DISCUSSION TITLE
How do you run a custom command?

### DISCUSSION THREAD

**Discussion by Milo123459** [starship/starship#1898] [Q&A] [answered]
In my config I have this:
```toml
[custom.powershell]
command = "echo 🚀"
when="true"
prefix = ""
```
But, when I open powershell, it doesn't echo anything?
