### DISCUSSION TITLE
Different starship.toml settings for bash/fish/zsh

### DISCUSSION THREAD

**Discussion by mattmc3** [starship/starship#1908] [Q&A] [answered]
I regularly use different shells, and would like to use starship to enhance the prompt for each of them. Unfortunately, if I do this, it can quickly become confusing to distinguish which shell I am in. A simple solution to this would be to use a different prompt symbol for each shell (eg: $ for bash, % for zsh, and > for fish), but I cannot find anywhere in the documentation how to do something like this. I would like to either:

1. Customize the settings in ~/.config/starship.toml for each shell
or
1. Have multiple starship.toml files and point the `starship init` calls to a different starship.toml file for each shell

Is there a way to do this? Did I miss something in the docs?

**Comment by matchai** [comment, marked as answer]
You can override the path to the Starship config by setting `STARSHIP_CONFIG` in your respective shells:

E.g. in `~/.config/fish/config.fish`
```fish
set -x STARSHIP_CONFIG ~/.config/starship-fish.toml
```

Then in `~/.zshrc`
```zsh
export STARSHIP_CONFIG=~/.starship-zsh.toml
```

**Comment by mickimnet** [comment]
You could also include three custom sections in the same `starship.toml` file, as did I:

```toml
[custom.bash]
description = "Show a shell symbol, if in a Bash shell"
command = "echo -n 🦪"
# command = "echo -n " # alternate
# command = "echo -n " # alternate
when = '[ "$STARSHIP_SHELL" == "bash" ]'
shell = ["bash", "--noprofile", "--norc"]
format = "[$output](bg:#AFD700 fg:#111111)[](bg:#464347 fg:#AFD700)"

[custom.fish]
description = "Show a fish symbol, if in a Fish shell"
command = "echo -n 🐠"
# command = "echo -n " # alternate
# command = "echo -n " # alternate
when = '[ "$STARSHIP_SHELL" == "fish" ]'
shell = ["bash", "--noprofile", "--norc"]
format = "[$output](bg:#AFD700 fg:#111111)[](bg:#464347 fg:#AFD700)"

[custom.zsh]
description = "Show a rocket symbol, if in a Zsh shell"
command = "echo -n 🚀"
# command = "echo -n " # alternate
# command = "echo -n " # alternate
when = '[ "$STARSHIP_SHELL" == "zsh" ]'
shell = ["bash", "--noprofile", "--norc"]
format = "[$output](bg:#AFD700 fg:#111111)[](bg:#464347 fg:#AFD700)"
```

You should change the format, as it is meant for my [prompt theme](https://github.com/mickimnet/myth-prompt-themes).
