### DISCUSSION TITLE
Having issues making git status work and vscode integrated terminal

### DISCUSSION THREAD

**Discussion by arzkar** [starship/starship#2083] [Q&A] [answered]
Git status symbols are not showing up in my system terminal as you can see in the below image.
![image](https://user-images.githubusercontent.com/70950611/103657709-3a7baa00-4f90-11eb-9ab3-a757ef3746b7.png)

Same thing as above and conda env symbol as well as the name are not showing up in the integrated terminal of VSCode.
![image](https://user-images.githubusercontent.com/70950611/103657929-8a5a7100-4f90-11eb-99ef-b9a2aa5c8a50.png)

My .bashrc-
```sh
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias pos-ff="./pos-ff.sh"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/rogueone/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/rogueone/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/rogueone/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/rogueone/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# cargo(rust)
source "$HOME/.cargo/env"

# starship powerline
eval "$(starship init bash)"
```
My starship.toml-
```toml
# Don't print a new line at the start of the prompt
add_newline = true

# Use custom format  $username
format = """ 
[╭─](white) $hostname in $directory$package$java$python$git_branch$battery$cmd_duration
[╰─](white)$character """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "#00ffff"
format = "[$user]($style) "
disabled = false

# Hostname settings
[hostname]
ssh_only = false
format =  "on [$hostname](#ff5f87)"
trim_at = ".companyname.com"
disabled = false

# Directory indicator
[directory]
read_only = "🔒"
style = "bold cyan"
read_only_style = "red"
truncation_length = 8 # 0 to show the full directory path
truncation_symbol = "…/"
format = "[$read_only]($read_only_style)[$path]($style) "
disabled = false

# Package Version Config
[package]
format = "via [🎁 $version](208 bold) "

# Python settings
[python]
# symbol = " "
symbol = "🐍 "
style = "yellow bold"
python_binary = "python3"
pyenv_version_name = true

# Conda settings
[conda]
format = "on [$symbol$environment ](dimmed green) "

# git settings
[git_branch]
# symbol = "🌱 "
style="bold #875fff"
truncation_length = 4
truncation_symbol = ""

[git_commit]
disabled = false
commit_hash_length = 4
# tag_symbol = "🔖 "
tag_disabled = false

[git_state]
disabled = false

# [git_status]
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"
# staged = '[++\($count\)](green)'

# Battery information
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 15
style = "bold red"

# cmd_duration config
[cmd_duration]
show_milliseconds = true
style = "bold #0087d7"
format = "took [$duration]($style)"

# Replace the "❯" symbol in the prompt with "➜"
[character]     # The name of the module we are configuring is "character"
format = "$symbol"                       
success_symbol = "[❯](#00ffff)" # λ
error_symbol = "[✗](bold red)" 
disabled = false

```
