### DISCUSSION TITLE
Check for background jobs in custom commands

### DISCUSSION THREAD

**Discussion by markschmidt** [starship/starship#2143] [Q&A] [answered]
Hi 👋 ,

I'm trying add some indicator to see if I have a running vim background instance in the current shell.
```toml
[custom.vim]
command = "echo ' [vim]'"
when = "jobs | grep -q vim"
```
It's never shown. Apparently the list of jobs is always empty (because a subshell is started?). Any idea how I can fix that?
