### DISCUSSION TITLE
Help with conditional formatting depending on multiple modules

### DISCUSSION THREAD

**Discussion by wlonkly** [starship/starship#2240] [Q&A]
Hey all! Just starting out with Starship, hoping to replace my somewhat fragile homegrown prompt as closely as possible. 

My homegrown prompt does the same kind of thing with `$username` and `$hostname` that Starship does, only displaying hostname over SSH and only displaying username if it's not "me". But I handle the cases like this, where the ~ is `$directory`. 

```   
~ $                   # case 1: no ssh, no special user
bob:~ $               # case 2: no ssh, special user
remotebox:~ $         # case 3: ssh, but no special user
bob@remotebox:~ $     # case 4: ssh and special user
```

(I use colors to differentiate between cases 2 and 3, but the colors are easy to figure out and hard to represent here, so I omitted them.)

The trick here is that `$username` ends with `:` if there's no hostname to display (case 2) or with `@` if there is a hostname to display (case 4). Is there a way to express that in Starship?

(**Quick update**: I realize now that case 3 will never apply with Starship since the username module shows a username on any SSH connection. But still, case 2 and 4 are the spot I'm stuck.)

**Comment by mickimnet** [comment]
Hello @wlonkly,

that is currently not possible. We have a couple of issues regarding the configuration format and other formatting options.

For the time being, I would recommend to create your own custom modules (e. g. a combined one for `$username` with `$hostname` and one for `$username` only.

I created my own, because I like to use special conditions for `tmux` on remote sessions. Maybe they can be an inspiration for you:

```toml
[custom.root]
# disabled = true
description = "Only display username, if sudo or different from standard user"
command = "echo $USER"
when = '[[ -z "$SSH_CONNECTION" ]] && ([[ -n "$SUDO_USER" ]] || [[ "$USER" != "$LOGNAME" ]])'
shell = ["bash", "--noprofile", "--norc"]
format = "[](bg:#FF5511 fg:#464347)[$output](bold bg:#FF5511 fg:#EEEEEE)[](bg:#464347 fg:#FF5511)"

[custom.ssh_user]
# disabled = true
description = "Display username, if on a ssh session, but not in tmux"
command = "echo $USER"
when = '([[ -n "$SSH_CONNECTION" ]] && [[ -z "$TMUX" ]]) && ([[ "$USER" != "root" ]] && [[ -z "$SUDO_USER" ]] && [[ "$USER" == "$LOGNAME" ]])'
shell = ["bash", "--noprofile", "--norc"]
format = "[](bg:#3388FF fg:#464347)[$output](bg:#3388FF fg:#EEEEEE)[](bg:#464347 fg:#3388FF)"

[custom.ssh_root]
# disabled = true
description = "Display username on a ssh session, if different from standard user"
command = "echo $USER"
when = '[[ -n "$SSH_CONNECTION" ]] && ([[ "$USER" == "root" ]] || [[ -n "$SUDO_USER" ]] || [[ "$USER" != "$LOGNAME" ]])'
shell = ["bash", "--noprofile", "--norc"]
format = "[](bg:#FF5511 fg:#464347)[$output](bold bg:#FF5511 fg:#EEEEEE)[](bg:#464347 fg:#FF5511)"
```

Take care
Mick
