### DISCUSSION TITLE
different icons to indicate current shell

### DISCUSSION THREAD

**Discussion by mvolkmann** [starship/starship#2473] [Q&A] [answered]
I sometimes switch between using fish shell, bash, and Nushell.
I'm using Starship in all of these.
I'd like to include an icon in my prompt that indicates which shell I'm in currently.
Is there a way to do that?

**Comment by mvolkmann** [comment, marked as answer]
I found a solution to this ... not sure if it's the best approach.
I defined the environment variable `SHELL_ICON` in the configuration script of each shell.
In `.bash_profile` I added `export SHELL_ICON=🚀`.
In `~/.config/fish/config.fish` I added `set -x SHELL_ICON 🐠`.
In `$(config path)` for Nushell I added `SHELL_ICON = "🦀"` in the `[env]` section.
Then I added this in `~/.config/starship.toml`:

```toml
[env_var]
format = "$env_value"
variable = "SHELL_ICON"
default = "?"
```
Finally, I added `$env_var` in the `format` string for the prompt.

**Reply by matchai** [reply]
Here's another way to do it entirely from within Starship config: https://github.com/starship/starship/discussions/1252#discussioncomment-18316

**Reply by mvolkmann** [reply]
Nice! I mostly copied that and ended up with this:

```toml
# Indicates when in bash shell.
[custom.bash]
command = "echo 🚀"
when = '[ "$STARSHIP_SHELL" == "bash" ]'

# Indicates when in fish shell.
[custom.fish]
command = "echo 🐠"
when = 'test "$STARSHIP_SHELL" = "fish"'

# Indicates when in Nushell.
[custom.nu]
command = "echo 🦀"
shell = 'bash'
when = '[ "$STARSHIP_SHELL" == "" ]' # not set in Nushell
```

Then I added `$custom` in my prompt to run all of those custom commands.
