### DISCUSSION TITLE
How to improve custom command timings?

### DISCUSSION THREAD

**Discussion by egvimo** [starship/starship#2534] [Q&A]
I have the following custom command (taken and adapted from [here](https://github.com/starship/starship/discussions/1252#discussioncomment-481286)):

```toml
[custom.git_email]
command = "git config user.email"
when = "git rev-parse --git-dir 2> $null"
format = "by [$output]($style) "
style = "bright-yellow"
```

But the timings from this command are quite slow.

```
❯ starship timings

 Here are the timings of modules in your prompt (>=1ms or output):
 git_email   -  988ms  -   by email@domain.com 
 git_status  -   89ms  -   [+⇡]
 java        -   52ms  -   via ☕ v11.0.8 
 nodejs      -   36ms  -   via  v14.16.0
...
```

I'm on Starship 0.51.0 in PowerShell.

I also tried to change the command (`Write-Host test`) and the condition (`git rev-parse --is-inside-work-tree 2> $null` or simply `when = "0"`) but with no luck.

How can I improve this?
Is there a way to dig deeper and find out why this custom module is so slow?

**Comment by davidkna** [comment]
Adding `shell = ["bash", "--noprofile", "--norc"]` might help.

**Reply by egvimo** [reply]
This is in a PowerShell. What would be the equivalent therefor?

**Reply by davidkna** [reply]
Starship already adds something like this by default for PowerShell.

**Reply by egvimo** [reply]
Is there anything else I can do?

**Comment by egvimo** [comment]
I've found a workaround using the Git shell from "Git for Windows":

```toml
[custom.git_email]
command = "git config user.email"
when = "git rev-parse --git-dir 2> /dev/null"
shell = ['C:\Program Files\Git\bin\sh.exe']
format = "by [$output]($style) "
style = "bright-yellow"
```

I suppose there might be better solutions, but this way I reduced the timing to ~150ms.
