### DISCUSSION TITLE
[WARN] - (starship::configs::python): Unknown config key 'scan_for_pyfiles'

### DISCUSSION THREAD

**Discussion by shinokada** [starship/starship#2630] [Q&A] [answered]
When I start a terminal I get the following warning:

```
[WARN] - (starship::configs::python): Unknown config key 'scan_for_pyfiles'
```

How can I fix this?

I  use macOS Big Sur, v11.2.3.

I have the following in `~/.config/starship.toml`:

```
...

[python]
disabled = false
pyenv_version_name = false
pyenv_prefix = "pyenv "
python_binary = "python"
scan_for_pyfiles = true
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
style = "yellow bold"
symbol = "🐍 "

...
```

**Comment by vladimyr** [comment, marked as answer]
That one is removed in `v0.51.0` https://github.com/starship/starship/commit/da4bd40

To achieve same effect you can use (applied to your config):
```toml
[python]
disabled = false
pyenv_version_name = false
pyenv_prefix = "pyenv "
python_binary = "python"
detect_extensions = []
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
style = "yellow bold"
symbol = "🐍 "
```

Default value for `detect_extensions` is `["py"]`.

**EDIT:**  I misinterpreted your intent. If you want to display the Python version whenever `.py` files are present just remove that legacy option and the `detect_extensions` default will kick in.
