### DISCUSSION TITLE
A series of icon modifications made for bitmap fonts

### DISCUSSION THREAD

**Discussion by tarsiec** [starship/starship#2875] [Show and tell]
I've recently configured starship to display [Siji](https://github.com/stark/siji) font's bitmap icons instead of the default ones. I figured someone else might appreciate it so I decided to leave it here:
(if you'd like to suggest a change, it do it in my dotfiles [repo](https://github.com/tarsiec/dotfiles))
```toml
[aws]
icon = " "
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
empty_symbol = " "
unknown_symbol = " "
[character]
success_symbol = "[>](green)"
error_symbol = "[?](bold red)[](red)"
vicmd_symbol = "[*](bold green)[](green)"
[cmake]
symbol = " "
[conda]
symbol = "C "
[directory]
read_only = " "
[elixir]
symbol = " "
[git_branch]
symbol = " "
[git_commit]
tag_symbol = " "
[git_status]
ahead = " "
behind = " "
diverged = " "
renamed = " "
deleted = "X"
[golang]
symbol = "GO "
[java]
symbol = "JAVA "
[jobs]
symbol = " "
[julia]
symbol = "∴ "
[kubernetes]
symbol = " "
[lua]
symbol = " "
[memory_usage]
symbol = " "
[nim]
symbol = " "
[nix_shell]
symbol = " "
[package]
symbol = " "
[python]
symbol = "PY "
[ruby]
symbol = " "
[rust]
symbol = "RS "
[shell]
powershell_indicator = " "
[shlvl]
symbol = " "
[time]
format = '[ $time]($style) '
[zig]
symbol = " "
```
Your browser may not display the symbols, but if you allow said font to be displayed in the terminals, the symbols will show up just fine.
