### DISCUSSION TITLE
command_timeout error

### DISCUSSION THREAD

**Discussion by cryskram** [starship/starship#2902] [Q&A] [answered]
Recently i added Starship to my zsh shell and after sometime I started getting this:
`[WARN] - (starship::utils): Executing command "elixir" timed out`

So a quick google search said me to add `command_timeout = 1000` in my starship config file
I did that, but later, once I reopened the terminal, I am getting this:
[WARN] - (starship::configs::character): Unknown config key 'command_timeout'   

Kindly let me know what to do, or is it a bug, or my config file error
[Here](https://pastebin.com/b2pap2JB) is my config file

**Comment by p403nix** [comment]
i'm facing this same issue... please help

**Comment by matchai** [comment, marked as answer]
Currently your `format` and `command_timeout` configuration options are beneath the `[character]` header:

```toml
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
 
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) """
 
command_timeout = 1000
```

They would need to be root-level, before any headers, to apply:

```toml
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) """
 
command_timeout = 1000

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
```

**Reply by cryskram** [reply]
thanks a lot mate... this solved it

**Reply by p403nix** [reply]
Hello my toml is totaly different, here it is below can tell me where i should put the command_timeout please?

```toml
## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [╭─$user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = " 🕙 $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 └─
[character]
success_symbol = " [╰─λ](bold red)"
error_symbol = " [×](bold red)"

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
```

i had it placed below the character and i still get  [WARN] - (starship::configs::character): Unknown config key 'command_timeout'
