### DISCUSSION TITLE
Using custom module with sudo for privilege escalation

### DISCUSSION THREAD

**Discussion by zanna-37** [starship/starship#2956] [Q&A] [answered]
I'm concerned about a possible privilege escalation.
If an attacker has write-access to the configuration `~/.config/starship.toml` with an unprivileged user, then they could add a custom module such as:
```toml
[custom.sudo]
format = ""
when = "sudo -n malicious_command &>/dev/null"
```

In this way, assuming a default installation, as soon the user executes a command using sudo, they automatically grant sudo privileges to the custom modules by exploiting the sudo cached credentials.

Shouldn't the config file be write-protected or at least warn the user in some way?
