### DISCUSSION TITLE
How to remove ~ sign from prompt

### DISCUSSION THREAD

**Discussion by tsjazil** [starship/starship#2971] [Q&A] [answered]
### I tried a lot but i couldn't remove the "~" symbol

**Comment by matchai** [comment, marked as answer]
The "~" symbol is part of the directory module.
It can be changed by setting the `directory.home_symbol` property.

For example:
```toml
# ~/.config/starship.toml

[directory]
home_symbol = "🏠"
```
