### DISCUSSION TITLE
Ansible task to install/upgrade Starship

### DISCUSSION THREAD

**Discussion by bradleyfrank** [starship/starship#3043] [Show and tell]
I recently wrote an Ansible task for installing Starship, thought I would share!

I set one of these variables:

```yaml
starship:
  download_path: /tmp/starship.tar.gz
  install_path: "{{ ansible_user_dir }}/.local/bin"
  tarball: https://github.com/starship/starship/releases/latest/download/starship-{{ ansible_architecture }}-apple-darwin.tar.gz
```

```yaml
starship:
  tarball: https://github.com/starship/starship/releases/latest/download/starship-{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  install_path: "{{ ansible_user_dir }}/.local/bin"
  download_path: /tmp/starship.tar.gz
```

And run this task:

```yaml
- name: Check if Starship is installed
  ansible.builtin.stat:
    path: "{{ starship['install_path'] }}/starship"
  register: starship_package

- name: Get installed version of Starship
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ starship['install_path'] }}"
  ansible.builtin.command: "starship --version"
  changed_when: false
  register: starship_version
  when: starship_package['stat']['exists']

- name: Get latest version of Starship
  community.general.github_release:
    user: starship
    repo: starship
    action: latest_release
  register: latest_version

- name: Run Starship installer
  vars:
    installed_version: "{{ starship_version['stdout'] | default('tag:v0.0.0') }}"
    version_local: "{{ installed_version | regex_search('tag:(.*)', '\\1') | first }}"
    version_remote: "{{ latest_version['tag'] }}"
  block:
    - name: Download Starship tarball
      ansible.builtin.get_url:
        url: "{{ starship['tarball'] }}"
        dest: "{{ starship['download_path'] }}"
        mode: 0644
    - name: Extract Starship exectuable
      ansible.builtin.unarchive:
        src: "{{ starship['download_path'] }}"
        dest: "{{ starship['install_path'] }}/"
    - name: Make Starship executable
      ansible.builtin.file:
        path: "{{ starship['install_path'] }}/starship"
        mode: 0755
  always:
    - name: Remove Starship tarball
      ansible.builtin.file:
        path: "{{ starship['download_path'] }}"
        state: absent
  when: version_local != version_remote
```
