### DISCUSSION TITLE
How would I define a custom command such that I can run a script "only" when I `cd` into a git directory

### DISCUSSION THREAD

**Discussion by NullVoxPopuli** [starship/starship#3061] [Q&A]
I have this in my config so far:
```
[custom.git-remotes]
command = 'git remote -v | grep fetch'
files = [".git/"]
when = """ test $PWD """ 
format = "[\n$output]($style)"
```
note my `when` is just "something" that would be "true"

My use case:
 - I do a fair bit of open source, and often need to work with different git remotes, and it would be handy to, when I first `cd` into a directory, have the remotes printed
 
 What I'm experiencing with the above custom command:
  - no output _until_ I get to a git directory (correct)
  - every `cd` within that git directory continues to print the remotes (do not want)

**Comment by matchai** [comment]
I think that [`direnv`](https://direnv.net/) may be better suited for what you're trying to do.
If you're looking to show the output of the command that was run when `cd`ing, you can store it in an environment variable and show it in starship with the [environment variable](https://starship.rs/config/#environment-variable) module.

**Reply by NullVoxPopuli** [reply]
> I think that direnv may be better 
> Before each prompt, direnv checks for the existence of a .envrc file in the current and parent directories

I don't think so :thinking: I don't want to have extra files in my repos :thinking: 

> with the environment variable module.

how would that help? it looks like this module is for _displaying_ env vars? 

ideally, what I need is something to the effect of:
```toml
[custom.git-remotes]
command = 'git remote -v | grep fetch'
files = [".git/"]
when = """ test $IS_NOW_IN_GIT_DIR && WASNT_IN_GIT_DIR  """
format = "[\n$output]($style)"
```
lol idk

**Reply by NullVoxPopuli** [reply]
best I can do atm, is:
```toml
[custom.git-remotes]
command = 'git remote -v | grep fetch'
files = [".git/"]
when = """ [ -d "$PWD/.git" ] """
format = "[\n$output]($style)"
```
which is fine if i never `cd` passed the root of a repo when I first start work in a repo :upside_down_face:
