### DISCUSSION TITLE
Moving time module to the right while keeping everything to left

### DISCUSSION THREAD

**Discussion by FrenzyExists** [starship/starship#3252] [Q&A] [answered]
Hi!, So, I've been checking the docs, and found that one can move stuff to the right using `format_right`, prob is, this sets whatever is after format_right to one line, my prompt is a two-line:

![image](https://user-images.githubusercontent.com/47986470/142747491-8cbade14-0869-4ebe-9fca-c5e45b0d370a.png)

Now, i tried using the `fill` module and welp, couldn't get what I wanted:

![image](https://user-images.githubusercontent.com/47986470/142747842-5ed7ca11-9a02-4fff-a93f-a0549f7f9ab7.png)

I tried using the fill over the right one, and just banishes anything that should be there.

This here is the part that is bugging me:

```
format = "$directory $git_branch $git_status $fill $time"
right_format = "$character"
add_newline = true

[fill]
symbol = " "
```

I don't think the rest helps, but gonna leave it here, this section is what you see in the first picture, in case anyone has no issue with the time being on the left and want to steal:

```
# A minimal left prompt

# move the rest of the prompt to the right


[character]
success_symbol = " [](blue) [](green) [](yellow) [](red)"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
format = '[$time]($style)'


[directory]
truncation_length = 50
truncate_to_repo = true
style = "yellow"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = 'ᛃ '
style = "cyan"
format = '[$symbol$branch]($style) '

[git_status]
deleted     = "[⤬](bold red) "
untracked   = "[⚶](bold cyan) "
stashed     = "[⇑](bold yellow) "
staged      = "[+](bold green) "
modified    = "[∆](bold green) "
renamed     = "[⥁](bold magenta] "
conflicted  = "[⥯](bold red) "
format = '([](black) [$all_status$ahead_behind]($style)) [](black) '


[lua]
symbol = ' '
format = '[$symbol]($style)'

[python]
symbol = ' '
format = '[$symbol]($style)'

[rust]
symbol = ' '
format = '\[[$symbol]($style)\]'

[kotlin]
symbol = '𝙆'
format = '\[[$symbol]($style)\]'

[java]
symbol = ''
format = '\[[$symbol]($style)\]'

[julia]
symbol = ''
format = '\[[$symbol]($style)\]'

[scala]
symbol = ''
format = '[$symbol]($style)'
```

**Comment by matchai** [comment, marked as answer]
`fill` and `right_format` serve similar purposes but aren't exactly alike. From the sounds of it, you'll want `fill`, but not `right_format`.
`fill` is best suited to spread out a single line of the prompt that does not accept user input.
`right_format` is for right-aligning modules on the same line as user input.

### To help illustrate
![image](https://user-images.githubusercontent.com/4658208/142756495-61a328a4-042d-4e71-b88a-44c193e9c852.png)

**Above (two-line prompt)**
```toml
# Space between modules and time with "fill"
format = """
$all\
$fill\
$time\
$line_break\
$character
"""

[fill]
# Make "fill" use space characters
symbol = " "

[time]
# Enable and format the time module
disabled = false
style = "bold bright-black"
format = "[$time]($style)"
```

**Below (one-line prompt)**
```toml
# Right-align the "time" module
right_format = "$time"

[line_break]
# Make it into a single-line prompt by disabling the line-break
disabled = true

[time]
# Enable and format the time module
disabled = false
style = "bold bright-black"
format = "[$time]($style)"
```
