### DISCUSSION TITLE
Different style for Kubernetes region_aliases

### DISCUSSION THREAD

**Discussion by guillaumewuip** [starship/starship#3273] [Q&A]
Hello Starship 👋

I would like to improve my kubernetes module by using style at the `context_aliases` level but it's apparently not supported : 

```toml
[kubernetes]
disabled = false
format = '[ $context(\($namespace\))](bold)'
[kubernetes.context_aliases]
"preprod" = '[preprod](green)'
"prod" = '[prod](red)'
```

This outputs `[preprod](green)` instead of `preprod` in green.

Is there another wait to to the same thing?
