### DISCUSSION TITLE
Modules in Right Prompt are now shown.

### DISCUSSION THREAD

**Discussion by eaxly** [starship/starship#3395] [Q&A] [answered]
Hey, there! Thank you for working on this!
A couple of hours ago, I discovered that you can configure starship to show output on the right side of the prompt. Naturally, I wanted to try it out.
I just couldn't seem to get it to work.

![Image](https://user-images.githubusercontent.com/62254492/148235981-fa859021-ab0c-4fbe-b7ed-5f71c7836553.png)

This should be the relevant part about my config.
```toml
add_newline = false

right_format = """
$status\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
"""
```

... but just to be safe.
```toml
add_newline = false

right_format = """
$status\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
"""

[character]
success_symbol = '[ͷ](bold dimmed green)'
error_symbol = '[ͷ](bold italic red)'
vicmd_symbol = '[Ͷ](bold purple)'

[line_break]
disabled = true  

[jobs]
number_threshold=3

[cmd_duration]
min_time = 50

[hostname]
ssh_only = false
format = '[@](bold dimmed yellow)[$hostname]($style)[\]](bold black) '
style = 'bold yellow'

[username]
show_always = true
format = '[\[](bold black)[$user]($style)'
style_user = 'bold red'
style_root = 'bold dimmed red'
disabled = false

[status]
format = "[↵ $status]($style)"
style = "bright-black"
disabled = false
```

I have already tried copy-pasting the [default right_prompt config here.](https://starship.rs/advanced-config/#enable-right-prompt) And that didn't work. Other prompts like [typewritten](https://github.com/reobin/typewritten) work completely fine though.
![image](https://user-images.githubusercontent.com/62254492/148236425-0bf78ae6-17c4-4f08-b960-1a01a1cf8305.png)

**Comment by eaxly** [comment]
Just to add more info, here is the output of `starship bug-report`:
```bash
pkg_version:1.1.1
tag:v1.1.1
commit_hash:9a4b2bb5
build_time:2021-12-24 18:02:40 +00:00
build_env:rustc 1.57.0 (Arch Linux rust 1:1.57.0-1)
```
...and `zsh --version`
```bash
zsh 5.8 (x86_64-pc-linux-gnu)
```
Have a fantastic day, 🚀!

~EDIT: Forgot to mention, I have tested it in bash, and doesn't work there either.~
EDIT2: Tested it on **fish** (a supported shell by starship) and doesn't work there either.

**Comment by matchai** [comment]
Looking at your first screenshot and configuration, only VCS-related modules are being put in the right-prompt, though it seems you're in your home directory. Nothing should appear differently.

Looking at the screenshot you shared when copy-pasting the "default right_prompt config", it seems to work correctly.
Your prompt character appears on the left and your directory is on the far right.

Here are a couple examples that can help illustrate how right prompts work:

![image](https://user-images.githubusercontent.com/4658208/148360074-8cb76764-13d1-4076-b9d1-24a9f790b9e8.png)

Here's the first prompt, making use of `$fill` for a two-line prompt:
```toml
format = """
$all\
$fill\
$time\
$line_break\
$character
"""

[fill]
symbol = " "

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"
```

Here's the second prompt on a single line, making use of `right_format`:
```toml
right_format = "$time"

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[line_break]
disabled = true
```
