### DISCUSSION TITLE
How to get rid of space when git status is clean?

### DISCUSSION THREAD

**Discussion by bschlenk** [starship/starship#3476] [Q&A] [answered]
I noticed there's an extra space in my prompt after the git branch, due to the space in the `git_status` config. Is there a way to make this take up zero space when nothing matches? This is my current config

```toml
[git_status]
format = "([$all_status$ahead_behind]($style)) "
diverged = "⇡⇣"
modified = "*" 
stashed = ""
```

| clean status | unstaged changes |
| --- | --- |
| <img width="54" alt="clean-status" src="https://user-images.githubusercontent.com/1390303/150396973-3c70da15-6556-412c-960e-706308389d16.png"> | <img width="58" alt="unstaged-changes" src="https://user-images.githubusercontent.com/1390303/150397051-f38005d0-37cd-4dcc-beb3-10729f5877ef.png"> |
