### DISCUSSION TITLE
Conditional styling in modules?

### DISCUSSION THREAD

**Discussion by mdhthahmd** [starship/starship#3497] [Q&A] [answered]
Hi,
I just started trying out starship and is trying customize my prompt to look something like powerlevel10k zsh theme.
i am almost done but there seems to be an issue with the chevrons, the yellow segment is for git and should be only visible when within a git repo, but a small yellow area can be seen from the prompt even when not within a repo

![image](https://user-images.githubusercontent.com/52692343/150765722-ffbd6143-7228-44a2-8308-c3bdfbdf405f.png)
i have looked into the the starship config and is now wondering if it is possible to fix this issue?

Here is my current config
```toml
# ~/.config/starship.toml

# Add blank lines between prompts
add_newline = true

# left prompt
format = """$env_var$username$directory$git_branch$git_status"""

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = "[ $env_value]($style)[](fg:white bg:#003543)"
style = "fg:#d70a53 bg:white"
variable = "STARSHIP_DISTRO"
disabled = false

[username]
style_user = "fg:#d4fc5c bold bg:#003543"
style_root = "red bold"
format = "[ $user ]($style)[](fg:#003543 bg:#0086d7)"
disabled = false
show_always = true

[directory]
truncation_length = 100
truncation_symbol = "…/"
style = "bold bg:#0086d7 fg:#003543"
format ="[  $path ]($style)[$read_only]($read_only_style)[](fg:#0086d7 bg:#d2ff5e)"


[git_branch]
truncation_length = 4
truncation_symbol = ""
format = "[ $symbol$branch ]($style)"
style="bg:#d2ff5e fg:#000000"

[git_status]
format = "[$all_status ]($style)[ ](fg:#d2ff5e bg:transparent)"
style = "bold bg:#d2ff5e fg:#000000"
```

ideally i want the yellow segment to be invisible completely
![image](https://user-images.githubusercontent.com/52692343/150767405-dfbcb074-1f44-48aa-8df8-3d75e12ac90f.png)

but from my understanding of the documentation it is not possible to conditionally apply style to a module
am i missing something or is there a workaround?

Thanks

**Comment by mdhthahmd** [comment, marked as answer]
so found out the solution, turns out i can use backspace (\b)

**Reply by pekkalaaksonen** [reply]
I can't get this to work. Where should I add the backspace?

**Reply by pekkalaaksonen** [reply]
Never mind, I figured it out!

**Reply by tessus** [reply]
can you maybe elaborate and tell us how?

**Reply by frolvanya** [reply]
> can you maybe elaborate and tell us how?

<img width="279" alt="image" src="https://github.com/starship/starship/assets/59515280/dffeb6d5-ac76-4bc6-8448-8bceaeab1f68">

I was able to do it like this:
```toml
format = """
$time\
$directory\
$git_branch\
$git_status \
"""

[time]
disabled = false
time_format = "%H:%M"
style = 'fg:#3B4252 bg:#88C0D0'
format = '[](fg:#88C0D0)[$time]($style)[](fg:#88C0D0)'

[directory]
truncate_to_repo = false
truncation_symbol = "…/"
style = 'fg:#E5E9F0 bg:#3B4252'
format = "\b[ ](fg:#88C0D0 bg:#3B4252)[$path]($style)[](fg:#3B4252)"

[git_branch]
symbol = " "
style = "fg:#3B4252 bg:#8FBCBB"
format = "\b[ ](fg:#3B4252 bg:#8FBCBB)[$symbol$branch(:$remote_branch)]($style)[](fg:#8FBCBB)"

[git_status]
conflicted = " $count "
ahead = "⇡ $count "
behind = "⇣ $count "
diverged = "⇕ $count "
untracked = " $count "
stashed = " $count "
modified = " $count "
staged = " $count "
renamed = " $count "
deleted = " $count "
style = "fg:#E5E9F0 bg:#5E81AC"
format = "\b[ ](fg:#8FBCBB bg:#5E81AC)[$conflicted$ahead$behind$diverged$untracked$stashed$modified$staged$renamed$deleted]($style)[](fg:#5E81AC)"
```

**Reply by tessus** [reply]
Thanks. I have been working on this for hours back when I asked that question, but got something working:

<img width="285" alt="image" src="https://github.com/starship/starship/assets/223439/fa7830c1-cb81-4445-be39-92f76aab44d0">

<img width="623" alt="image" src="https://github.com/starship/starship/assets/223439/bf2d0267-055d-492e-a6cd-ec0b09ef296c">

<img width="375" alt="image" src="https://github.com/starship/starship/assets/223439/36edf375-a284-4a41-84b5-1b17d152dec8">

Unfortunately there are a few things that just do not work properly, because it is not possible to work with conditional backreferences. Anyway, I am mostly happy with my setup now.

Here's my config:

```toml
#---------------------------------------------------------------------------#
# starship.toml
# Helmut K. C. Tessarek, Last update 2024-02-18
#---------------------------------------------------------------------------#

#---------------------------------------------------------------------------#
# Prompt format
#---------------------------------------------------------------------------#
format = """
$os\
$username\
[](fg:username_bg bg:hostname_bg)\
$hostname\
[](fg:hostname_bg bg:status_bg)\
$status\
[](fg:status_bg bg:directory_bg)\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state
"""

#---------------------------------------------------------------------------#
# These would have to be placed between
# - status and directory
# - directory and git
#---------------------------------------------------------------------------#
#[](fg:#FCA17D bg:#86BBD8)\
#$c\
#$elixir\
#$elm\
#$golang\
#$gradle\
#$haskell\
#$java\
#$julia\
#$nodejs\
#$nim\
#$rust\
#$scala\
#[](fg:#86BBD8 bg:#06969A)\
#$docker_context\
#[](fg:#06969A bg:#33658A)\
#$time\
#[ ](fg:#33658A)\


#---------------------------------------------------------------------------#
# Timeout for commands executed by starship (in milliseconds). default: 500
#---------------------------------------------------------------------------#
# We need it this high for retrieving remote git info
command_timeout = 2500

#---------------------------------------------------------------------------#
# Disable the blank line at the start of the prompt
#---------------------------------------------------------------------------#
#add_newline = false

palette = 'evermeet'

#---------------------------------------------------------------------------#
# Colors for prompt
#---------------------------------------------------------------------------#
[palettes.evermeet]
username_fg = 'bright-green'
username_bg = '#3c3c3c'
username_root_fg = 'bright-red'
username_root_bg = '#3c3c3c'
os_fg = '#c7c7c7'
os_bg = '#3c3c3c'
hostname_fg = '#181818'
hostname_bg = '#00ffff'
status_fg = '#FFFFFF'
status_bg = '#DA627D'
directory_bg = '#33658A'
directory_fg = '#FFFFFF'
git_fg = '#000000'
git_bg = '#d2ff5e'

#---------------------------------------------------------------------------#
# Module Configs
#---------------------------------------------------------------------------#
[os]
format = '[ $symbol]($style)'
style = "fg:os_fg bg:os_bg"
# Enable the OS Info
#disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:username_fg bg:username_bg"
style_root = "fg:username_root_fg bg:username_root_bg"
format = '[ $user ]($style)'
disabled = false

[hostname]
ssh_only = false
trim_at = '.'
style = "fg:hostname_fg bg:hostname_bg"
format = '[ $hostname ]($style)'

[status]
format = '[ $status ]($style)'
style = 'fg:status_fg bg:status_bg'
disabled = false

[directory]
style = 'bold bg:directory_bg fg:directory_fg'
read_only_style = 'bg:directory_bg'
format = '[ $path ]($style)([$read_only ]($read_only_style))[ ](fg:directory_bg)'
truncation_length = 9
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
always_show_remote = true
#only_attached = false
style = "fg:git_fg bg:git_bg"
format = "\b\b[](fg:directory_bg bg:git_bg)[ $symbol $branch( {$remote_name:$remote_branch}) ]($style)[ ](fg:git_bg)"

[git_status]
style = "fg:git_fg bg:git_bg"
format = "(\b\b[$all_status$ahead_behind ]($style)[ ](fg:git_bg))"
staged = '●${count} '
conflicted = '⭑ '
stashed = '⚑ '
ahead = '⬆ ${count} '
behind = '⬇ ${count} '
diverged = '⭥ '
#diverged = '⇕⇡${ahead_count}⇣${behind_count}'
modified = '✚${count} '
untracked = '…${count} '
# a few symbols: ↓⇩⬇⬆ ⭡⭣⬍⬍⬆⇵↕⭥

[git_commit]
style = "fg:git_fg bg:git_bg"
tag_disabled = false
tag_symbol = ' ☖ '
format = "[([\b\b](fg:directory_bg bg:git_bg) $hash$tag )]($style)[ ](fg:git_bg)"

[git_state]
style = "fg:git_fg bg:git_bg"
format = "(\b\b[$state( $progress_current/$progress_total) ]($style))[ ](fg:git_bg)"

#---------------------------------------------------------------------------#
# Not currently used
#---------------------------------------------------------------------------#
[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

```
