### DISCUSSION TITLE
Is there a way to not render a module when a variable is None?

### DISCUSSION THREAD

**Discussion by DarkVanityOfLight** [starship/starship#3539] [Q&A]
# What I want
I want to display the git_branch surrounded by $fill and a $line_break. The problem is that I can't make the $fill and $line_break disappear when the $git_branch is none.

# What I have
```toml
format="""$fill$directory$fill$line_break\
$fill$git_branch$fill$line_break\
$character"""
add_newline=false

[directory]
style = "#E57EE4"
truncation_length = 0

[fill]
style="bold #6A8FFB"
symbol="─"

[character]
success_symbol = "[λ](bold #E57EE4)"
error_symbol = "[×](bold red)"

[git_branch]
style="#9F3591"
```
Will produce something like this:
```
─────MyGitProject ─────
─────on  my_branch ───
λ
```
Or if not in a repository:
```
─────AnotherDirectory ─────
──────────────────
λ
```
This is not what I want, I want this if not in a GIT repo:
```
─────AnotherDirectory ─────
λ
```

# What I tried
From my undestanding this should be possible by using a conditional format string, so I tried that:
```toml
format="""$fill$directory$fill$line_break\
[($fill$git_branch$fill$line_break)]()\
$character"""
```
But that also produces the output above, because it only won't render if ALL variables are none, I just don't want to output the rest if ONE of them is none. I feel like this should be possible but I m just to stupid to do it.
