### DISCUSSION TITLE
Extend default configuration

### DISCUSSION THREAD

**Discussion by 0x3333** [starship/starship#3765] [Q&A]
I want to extend the Java detect_files configuration, I want to add "build.xml" to it. Currently, I need to set the default + my config, like:

```toml
[java]
detect_files = ["build.xml", "pom.xml", "build.gradle.kts", "build.sbt", ".java-version", ".deps.edn", "project.clj", "build.boot"]
```

I couldn't find an option to extend, something like:

```toml
[java]
detect_files = ["$detect_files", "build.xml"]
```

Is that possible?
