### DISCUSSION TITLE
Git branch name/status Error?

### DISCUSSION THREAD

**Discussion by Pat-Lafon** [starship/starship#4111] [Q&A]
Hi, sorry if I missed a recent change but I'm getting the following error and I haven't made any changes to my config file:

```
[WARN] - (starship::config): Failed to load config value: Error in 'GitStatus' at 'staged': invalid type: map, expected a borrowed string
```

My toml file contains the following:
```toml
[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged.enabled = true
renamed = "👅"
deleted = "🗑"
```

Currently getting the following in my terminal:
```
bril on 🌱 floats [$!?] 
❯ 
```

What changes do I need to make to convert `[$!?] ` back to the git-branch name/status?
