### DISCUSSION TITLE
Why do I have this world icon by default?

### DISCUSSION THREAD

**Discussion by rwjack** [starship/starship#4770] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/59068073/209835689-42732658-039a-45e9-92fd-37e2ca893d8c.png)

This on an ssh'd machine.

starship.toml
```toml
# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"

# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
```

**Comment by chipbuster** [comment, marked as answer]
Does `starship explain` tell you where the icon is coming from?

**Reply by rwjack** [reply]
```
root in 🌐 x-ray in ~ ❯ starship explain

 Here's a breakdown of your prompt:
 "root in " (<1ms)      -  The active user's username
 "🌐 x-ray in " (<1ms)  -  The system hostname
 "~ " (<1ms)            -  The current working directory
 "❯ " (<1ms)            -  A character (usually an arrow) beside where the text is entered in your terminal
root in 🌐 x-ray in ~ ❯ vi /etc/hostname
root in 🌐 x-ray in ~ ❯ hostnamectl set-hostname x-ray
root in 🌐 x-ray in ~ ❯ cat /etc/hostname
x-ray
```

System hostname, makes absolutely no sense. I haven't reinstalled any VMs lately except this one, so I thought it might be a newer version of starship that has something enabled by default, but this just makes 0 sense.

**Reply by rwjack** [reply]
All my other hosts have starship `1.6.3`, while this one has `1.11.0`.

**Reply by jankatins** [reply]
Have a look at https://starship.rs/config/#hostname, it's the default ssh symbol. If you don't want it, change the symbol to an empty string or change the format string to not contain the ssh_symbol variable.

**Reply by rwjack** [reply]
Thanks everyone!

This solved it for me:
```toml
[hostname]
ssh_symbol = ""
```
