### DISCUSSION TITLE
can I use conditional style?

### DISCUSSION THREAD

**Discussion by GrayKwon** [starship/starship#4864] [Q&A]
i want change style each framework

my code

```toml
[custom.nodejs]
detect_files = ["package.json"]
format = '$output'
command = """
PACKAGE=$(cat ./package.json)
REACT=$(echo $PACKAGE | grep -w react)
NUXT=$(echo $PACKAGE | grep -w nuxt)
if [[ ${#REACT} -ne 0 ]]; then
  SYMBOL=""
  COLOR="#248ed3"
elif [[ ${#NUXT} -ne 0 ]]; then
  SYMBOL=""
  COLOR="#41b883"
else 
  SYMBOL=""
  COLOR="#8bc34a"
fi
echo "$SYMBOL"
"""
```

in this case how to use COLOR variable?
