### DISCUSSION TITLE
HELP! starship will crush when activate conda

### DISCUSSION THREAD

**Discussion by Gandharikos** [starship/starship#4964] [Q&A]
This is Powerlevel10K, 
![2023-03-06_15-06](https://user-images.githubusercontent.com/12139734/223042324-84b53378-aeb9-4097-a57e-e1cfb16e967d.png)
This is starship
![2023-03-06_15-09](https://user-images.githubusercontent.com/12139734/223042332-dc3f7d58-0f8e-4ff5-85b7-7c028a83345b.png)
---
This is my starship config
```toml
# Use custom format:
format='''
$directory$git_branch$git_status$conda$docker_context
$character
'''

# Prompt symbols
[character]
success_symbol = "[](#9ece6a bold)"
error_symbol = "[](#db4b4b)"
vicmd_symbol = "[](#9ece6a)"
vimcmd_replace_one_symbol = "[](#d19a66)"
vimcmd_replace_symbol = "[](#e0af6e)"
vimcmd_visual_symbol = "[](#c678dd)"

[os]
format = "[]($style)[$symbol](bg:#292E42 fg:#7aa2f7)"
# style = "bg:#292E42 fg:#7aa2f7"
style = "bg:#1a1b26 fg:#292E42"

[os.symbols]
Windows = " "
Macos = " "
FreeBSD = " "
Android = "󰀲 "
Alpine = " "
Amazon = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
Garuda = " "
Gentoo = " "
HardenedBSD = " "
Illumos = " "
Linux = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "

[directory]
read_only = "  "
read_only_style = "bg:#292E42 fg:#db4b4b"
format = "[]($style)[ ](bg:#292E42 fg:#7aa2f7)[[$path](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)[$read_only]($read_only_style)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[git_branch]
symbol = " "
format = "[]($style)[[$symbol](bg:#292E42 fg:#9ece6a)[$branch](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)"
style = "bg:#1a1b26 fg:#292E42"

[git_status]
format = "[$all_status$ahead_behind]($style)[](bg:#1a1b26 fg:#292E42)"
style = "bg:#292E42 fg:#db4b4b"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "
format = "[]($style)[$symbol$environment](bold green)[]($style)"
style = "bg:#1a1b26 fg:#292E42"

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "[]($style)[$symbol$context](blue bold)[]($style)"
style = "bg:#1a1b26 fg:#292E42"

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

```
