### DISCUSSION TITLE
Help with starship customization with git

### DISCUSSION THREAD

**Discussion by RiteshChepuri** [starship/starship#5197] [Q&A] [answered]
I'm trying to achieve this 
![Screenshot from 2023-05-22 08-15-13](https://github.com/starship/starship/assets/81766942/14d21102-10fb-4cea-afe7-358226c2867b)

**Comment by mickimnet** [comment]
Are you referring to the symbols, used in the `git` module, or the _Powerline_ style?

**Reply by RiteshChepuri** [reply]
in the git module which shows no of changes made, untracked files and so on..

**Reply by mickimnet** [reply, marked as answer]
Ah! I get it. You need to add `${count}` in the `[git_status]` section, see below for an example:

```toml
[git_status]
style = "bg:color_git_status fg:color_foreground_dark"
staged = " ${count}" # nf-fa-check
modified = "  ${count}" # nf-fa-edit
renamed = "󰗧${count}" # nf-md-cursor_text
untracked = " ${count}" # nf-fa-question
deleted = "  ${count}" # nf-fa-remove
conflicted = "${count}" # nf-fa-flag
stashed = "  ${count}" # nf-fa-bank
up_to_date = ""
ahead = "󰞙 ${count}" # nf-md-arrow_expand_up
behind = "󰞖 ${count}" # nf-md-arrow_expand_down
diverged = "󰡏 ${ahead_count} ${behind_count}" # nf-md-arrow_expand_vertical
format = "[($staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind )]($style)"
```
Configuration taken from my [theme](https://github.com/mickimnet/myth-prompt-themes).
