### DISCUSSION TITLE
How do I remove this docker text from my prompt?

### DISCUSSION THREAD

**Discussion by andradei** [starship/starship#5246] [Q&A] [answered]
I'm using Arch on WSL, which is based on some docker image, and this `[Docker ]` text shows up. How do I remove it?

![image](https://github.com/starship/starship/assets/2653546/aa43a664-adee-4886-9b94-77af55c7c963)

I tried this (my whole config)
```toml
# ~/.config/starship.toml

[docker_context]
disabled = true
```
