### DISCUSSION TITLE
[Poll] Is it a good idea for starship to connect to the internet as a default?

### DISCUSSION THREAD

**Discussion by Cyanide-1** [starship/starship#5263] [Polls]
As the title says, i am taking a poll on what people think about the current default config, currently, it pulls editor completions based on the config schema from the web, im personally against this as i think it would be a better idea for it to pull editor completions from locally installed files that come pre-packaged with starship as a default, the shell shouldn't be connecting to the internet, at least not as a default, not everyone has good internet speeds and may have unreliable internet, as well as some people (like myself) may feel uncomfortable with something that should fully run locally with all features included to connect to the internet as a default.

Thats just my personal reasoning though, im happy to hear what the rest of the community thinks about my suggestion.

**Comment by ghost** [comment]
+1 the last thing a shell prompt should do is connect to the internet

**Comment by Cyanide-1** [comment]
For anyone not in the know, the default config suggested on the website (https://starship.rs/config/#prompt) pulls editor completions from the internet, i dont feel comfortable with my shell prompt making network connections and i think this behavior should be changed by default to only pull from local files.

**Comment by matchai** [comment]
To be clear, Starship itself never makes network requests without confirmation, as it does when running `starship bug-report`.

The inclusion of the `$schema` key in your config causes your editor to make a network request to fetch the latest configuration schema:
```toml
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'

```

You're welcome to remove the `$schema` key to avoid making requests to `starship.rs`.
