### DISCUSSION TITLE
Getting extra blank spaces that does not seem to obey the styles, and are basically transparent

### DISCUSSION THREAD

**Discussion by rmsValue9232** [starship/starship#5272] [Q&A]
![Screenshot 2023-06-24 043643](https://github.com/starship/starship/assets/107769130/833e3d79-c019-4320-8e37-12be91e1c2ef)

These blank spaces are somehow appearing out of nowhere, and it does not seem to be coming from the config file as they are not following the styles of particular modules they appear in. In VS Code Integrated terminal, the blank space from `cmd_duration` module disappears as it should, while the blank space of the module `shell` appears in both places.
My font is CaskaydiaCove Nerd Font, and I also tried replacing the bash icon with an alphabet character, which clears out the possibility of font inconsistency.
How can I fix this?
I am using a color variant of the Tokyo Night Preset for the config file as follows:
```toml
format = """
[╭](c6)\
$shell\
$os\
[](bg:c5 fg:c6)\
$directory\
[](fg:c5 bg:c4)\
$git_branch\
$git_status\
$git_metrics\
[](fg:c4 bg:c3)\
$nodejs\
$rust\
$golang\
$php\
[](fg:c3 bg:c2)\
$cmd_duration\
[](bg:c1 fg:c2)\
$time\
[ ](fg:c1)\
\n[╰╶$character](c6)
"""

add_newline = false

palette = 'starrynight'

[palettes.starrynight]
c1 = '#161B27'
c2 = '#212736'
c3 = '#394260'
c4 = '#54618C'
c5 = '#769FF0'
c6 = '#A3AED2'
fgdark = '#111317'
fglight = '#f2f3f7'

[os]
format = "[$symbol]($style)"
style = "bg:c6 fg:fgdark"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[shell]
bash_indicator = " "
zsh_indicator = "%_"
fish_indicator = '󰈺 '
cmd_indicator = " "
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'bold bg:c6 fg:fgdark'
disabled = false

[username]
format ="[$user]($style)"
style_user = "bg:c6 fg:fgdark"
show_always = true

[directory]
style = "fg:fgdark bg:c5"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = " /"

[directory.substitutions]
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[git_branch]
symbol = ""
style = "bg:c4"
format = '[[ $symbol $branch ](bold fg:fglight bg:c4)]($style)'

[git_status]
style = "bg:c4"
format = '[[($all_status$ahead_behind )](bold fg:fglight bg:c4)]($style)'

[git_metrics]
added_style = "bold fg:green bg:c4"
deleted_style = "bold fg:red bg:c4"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false

[nodejs]
symbol = ""
style = "bg:c3"
format = '[[ $symbol ($version) ](fg:fglight bg:c3)]($style)'

[rust]
symbol = ""
style = "bg:c3"
format = '[[ $symbol ($version) ](fg:fglight bg:c3)]($style)'

[golang]
symbol = ""
style = "bg:c3"
format = '[[ $symbol ($version) ](fg:fglight bg:c3)]($style)'

[php]
symbol = ""
style = "bg:c3"
format = '[[ $symbol ($version) ](fg:fglight bg:c3)]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bg:c2"
format = "[[ 羽$duration ](fg:fglight bg:c2)]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:c1"
format = '[[  $time ](fg:fglight bg:c1)]($style)'

[character]
format = "$symbol"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
```
