### DISCUSSION TITLE
How to custom configure the module to customize the display position

### DISCUSSION THREAD

**Discussion by ghost** [starship/starship#5288] [Q&A] [answered]
### my configuration:
```
[username]
style_user = "bg:#33cc40 fg:#f8c836"
style_root = "bg:#f44336 fg:#f8c836"

format = "[Hello]($style) [$user](fg:#f8c836)"
disabled = false
show_always = true

[cmd_duration]
min_time = 1_000
show_milliseconds = false
format = "⏱️=[$duration](fg:#deeeeb)"
[status]
format = """
[$symbol$signal_name code=$int]($style)
"""
style = 'fg:#33cc40'    
symbol = '[🔴Error] (fg:#f44336)'
success_symbol = "[🟢 Success](fg:#33cc40)"
not_executable_symbol = '🚫Cant executable' 
not_found_symbol = '🔍Command not found'
sigint_symbol = '🔙' 
map_symbol = false
recognize_signal_code = true
disabled = false
```

### Example images:
![image](https://github.com/starship/starship/assets/118535944/e164216f-4c30-46fe-afa6-464029a5ad2c)

### Question: How to customize the display position?
For example, I want to put the command uptime is displayed in the code=0 behind.

`[status]
format = """
[$symbol$signal_name code=$int]($style) $cmd_duration
"""
`
i try Add **$cmd_duration** but no effect.

![image](https://github.com/starship/starship/assets/118535944/06328bb6-8105-4339-92b5-b313fc688382)

**Comment by mickimnet** [comment]
I'm not certain, what you are trying to accomplish. Did you check the general `format` section, where you can define the order of the modules—see: [Default Prompt Format](https://starship.rs/config/#prompt)?

**Reply by ghost** [reply]
I'm sorry I maybe the expression is not clear enough, my English is  bad.
I mean, I want to put ⏱️= 11s display hello front.
eg:⏱️=18s Hello Administrator 📌 🏠

### Current
`format = "[Hello]($style) [$user](fg:#f8c836)"`

### Revised
 `format = "$[cmd_duration][Hello]($style) [$user](fg:#f8c836)"`

I try to put cmd_duration at the beginning.
But it is still shown at the end as shown in the picture.

![image](https://github.com/starship/starship/assets/118535944/88493a5f-3109-4147-abea-f2ffa0a3c78d)

**Reply by mickimnet** [reply]
Yes, I did understand you correctly. You need to change that in the **general** `format` section—details are in the above mentioned link.

**Reply by mickimnet** [reply, marked as answer]
Is this, what you're looking for?
<img width="940" alt="image" src="https://github.com/starship/starship/assets/2911922/b6a0b236-7b19-42da-9ec8-4c9266113f3b">
If yes, this is the `starship.toml`, based on your configuration.
```toml
format = '$cmd_duration$username$all'

[username]
style_user = "bg:#33cc40 fg:#f8c836"
style_root = "bg:#f44336 fg:#f8c836"
format = "[Hello]($style) [$user ](fg:#f8c836)"
disabled = false
show_always = true

[cmd_duration]
min_time = 1_000
show_milliseconds = false
format = "⏱️=[$duration ](fg:#deeeeb)"

[status]
format = "[$symbol$signal_name code=$int]($style)"
style = 'fg:#33cc40'
symbol = '[🔴Error](fg:#f44336)'
success_symbol = "[🟢 Success](fg:#33cc40)"
not_executable_symbol = '🚫Cant executable'
not_found_symbol = '🔍Command not found'
sigint_symbol = '🔙'
map_symbol = false
recognize_signal_code = true
disabled = false
```
I also fixed some errors.
