### DISCUSSION TITLE
`right_format` Not Flush With Consoles Side

### DISCUSSION THREAD

**Discussion by SaltSouls** [starship/starship#5395] [Q&A] [answered]
I don't really know how to explain this but after formatting part of my console using `right_format` I noticed it wasn't flush with the right side of my console like the left is. I looked through my formatting to see if maybe I added a space where there shouldn't be, but found nothing. I know that this isn't normal behavior as I've seen other peoples starship setups and they don't have these weird spaces in them.

**Config settings:**
![Screenshot_20230821_175005](https://github.com/starship/starship/assets/36361103/81974c2f-7683-4aac-9265-4ace4d810f1c)

**Console appearance:**
![Screenshot_20230821_174859](https://github.com/starship/starship/assets/36361103/b53963f9-c37c-457c-9785-632f7d33606c)

**Comment by mickimnet** [comment]
What terminal, shell and font are you using?

Also, next time, please include your configuration as text, and not as a screenshot. That way it would be possible to try your configuration.

**Reply by SaltSouls** [reply]
Sorry, I should have specified. I'm using alacritty and zsh. I know I'm using one of the nerd fonts for the terminal, but I can't remember which one off the top of my head. Currently away from my PC.

**Reply by mickimnet** [reply]
I took the time to copy your configuration and try it out. The problem with the `[character]` is based on the default format value (`format = '$symbol '`), which contains a space at the end. Also, your `[time]` module contains an error at the end. The following configuration works on my system with _Fish Shell_ and with _Zsh_.
```toml
# ~/.config/starship/starship.toml
add_newline = false
format = "$username$directory"
right_format = "$character"

[character]
success_symbol = "[](fg:#262627)[](bg:#262627 fg:#3b3b3d)[ 󰄬 ](bold bg:#3b3b3d fg:green)"
error_symbol = "[](fg:#262627)[](bq:#262627 fq:#3b3b3d)[ × ](bold bq:#3b3b3d fq:red)"
format = '$symbol' # the default format contains a space after the $symbol variable

[directory]
disabled = false
truncation_length = 3
truncation_symbol = ".../"
home_symbol = "~"
read_only = "\uf023 "
read_only_style = "red"
format = "[ $path [$read_only](fg:red bg:#2587be)](bg:#2587be)[ ](fg:#2587be)"

[username]
disabled = false
show_always = true
style_user = "black"
style_root = "red"
format = "[  [$user ](bold bg:white fg:$style)](bold bg:white fg:$style)[](bg:#2587be fg:white)"

[time]
disabled = false
format = "[](bg:#3b3b3d fg:#636366)[](bg:#636366 fg:white)[ $time ](bold bg:white fg:black)"
time_range = "00:00:00-00:00:00"

[rust]
symbol = "\ue07a"
```

**Reply by SaltSouls** [reply]
So this fixed the double space, but there still seems to be a single space between the edge of the right side and where the symbol starts.
![image](https://github.com/starship/starship/assets/36361103/c3b95435-9dd3-45a2-9a5d-3fb7833adc73)
Current Config:
```toml
# ~/.config/starship/starship.toml
add_newline = false
format = "$username$directory$rust"
right_format = "$character"

[character]
success_symbol = "[](fg:#262627)[](bg:#262627 fg:#3b3b3d)[ ✓ ](bold bg:#3b3b3d fg:green)"
error_symbol = "[](fg:#262627)[](bg:#262627 fg:#3b3b3d)[ ✕ ](bold bg:#3b3b3d fg:red)"
format = "$symbol"

[directory]
disabled = false
truncation_length = 3
truncation_symbol = ".../"
home_symbol = "~"
read_only = "\uf023 "
read_only_style = "red"
format = "[ $path [$read_only](fg:red bg:#2587be)](bg:#2587be)[ ](fg:#2587be)"

[username]
disabled = false
show_always = true
style_user = "black"
style_root = "red"
format = "[  [$user ](bold bg:white fg:$style)](bold bg:white fg:$style)[](bg:#2587be fg:white)"

[time]
disabled = false
format = "[](bg:#3b3b3d fg:#636366)[](bg:#636366 fg:white)[ $time ](bold bg:white fg:black)"
time_range = "01:00:00-24:59:59"

[rust]
symbol = "\ue07a"
```
