### DISCUSSION TITLE
Create alias for the default profile in AWS CLI

### DISCUSSION THREAD

**Discussion by r-priyam** [starship/starship#5422] [Q&A]
I have a default profile in the AWS CLI config and when I open the terminal it doesn't show the profile name for me since it's a default one.

How can I show the alias for the default profile please?

I tried -
```toml
[aws]
format = 'on [$symbol$profile]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.profile_aliases]
default = 'Foo'
```
but it doesn't work
