### DISCUSSION TITLE
Is it possible to change the color of a git_branch based on the status returned by git_status?

### DISCUSSION THREAD

**Discussion by eatradish** [starship/starship#5440] [Q&A]
```toml
format = "$username$hostname \\[ [$directory](white)[$git_branch]($git_status) \\] [\\$](bold green) "

add_newline = false

[username]
format = "[$user](bold green)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@$hostname'
disabled = false

[directory]
format = "$path"

[git_branch]
format = "@$branch"

[git_status]
format = "$ahead_behind"
up_to_date = "bold green"
```

It doesn't work.

expected:

![图片](https://github.com/starship/starship/assets/19554922/cfbf0021-cdf7-484b-a146-c70df7e90a24)

starship:

![图片](https://github.com/starship/starship/assets/19554922/9f462936-e2b3-465f-b264-5e2b40005777)
