### DISCUSSION TITLE
Filtering text?

### DISCUSSION THREAD

**Discussion by mattieb** [starship/starship#5482] [General]
I have a Very Long Environment Variable and some clear rules for cutting unnecessary information out of it that I could easily represent as a regex.

Is there a built-in way to filter either variables or a format with a regex? I haven't seen anything, but I might just be missing something, too.

I think this could be useful for more than just environment variables.

**Comment by mattieb** [comment]
I did come up with this custom command for my specific need:

```toml
[custom.email]
when = "[ ! -z \"${EMAIL}\" ]"
command = "echo ${EMAIL} | sed -e 's/^\\(.\\).*@/\\1…@/'"
format = "[$output](blue) "
```

This section's job is to translate `impossibly.long.corporate.name@corp.com` to `i…@corp.com`.
