### DISCUSSION TITLE
Custom prompt inside non-Python virtual environment

### DISCUSSION THREAD

**Discussion by jdholtz** [starship/starship#5503] [Q&A] [answered]
Hey everyone. I currently have a project that implements a similar concept to Python's virtualenv but for Arch Linux's Pacman (found [here](https://github.com/jdholtz/pacman-venv)). It changes the prompt in the same way virtualenv does. Currently, a user is having an issue with the prompt change not appearing when using my project. 

I looked at how Starship customizes prompts and it appears to use the `VIRTUAL_ENV` environment variable. However, it also displays the Python version too, which doesn't make sense for my project. How can I customize the prompt to display something similar to virtualenv without it needing to be directly handled in Starship? Thanks!

**Comment by davidkna** [comment, marked as answer]
Without an official module in starship, a [`custom`](https://starship.rs/config/#custom-commands) or an [`env_var`](https://starship.rs/config/#environment-variable) can likely achieve this, e.g.:
```toml
[env_vars."_PACMAN_VENV"]
format = "Pacman Env [$env_value]($style) "
```

In general, the details of how the prompt is shown differ from shell-to-shell. For instance, on bash the `PS1`-value is replaced where with zsh the `PROMPT` is not changed after initial set-up.

**Reply by jdholtz** [reply]
The custom configuration section works perfectly for this. Thanks!

To note, I did the following for Bash:
```toml
[custom.pacman_venv]
command = '''basename "${_PACMAN_VENV}"'''
when = '''[[ -n "${_PACMAN_VENV}" ]]'''
format = '[\[$output\] ]($style)'
```
