### DISCUSSION TITLE
How'd i ignore my battery on a certain percentage

### DISCUSSION THREAD

**Discussion by pwnwriter** [starship/starship#5542] [General]
I've gone through the docx, i've got this

```toml
[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['main']
format = "[$branch]($style) "
style = " rosewater"
```

which basically ignores to show while on the main branch. Can i do something similar?
```toml
[battery]
full_symbol = "󱈑"
charging_symbol = "󰂄"
discharging_symbol = "󰂌"
# ignore_percentage= ['<90', '>15'] 
unknown_symbol = "󰂑"
format = "[$symbol]($style) $percentage"

[[battery.display]]
style = "italic mauve"
threshold=100
```

I don't want to show battery stuffs when the percentage is in between `15-90`

**Comment by davidkna** [comment]
Setting the style to `hidden` could work. As a warning this, could also cause issues with width computations between starship, your shell and your terminal emulator.

**Reply by pwnwriter** [reply]
> Setting the style to hidden could work

Can you please be more specific? an example?

**Reply by mickimnet** [reply]
I think _davidkna_ meant you to use the _hidden_ color option for styles (see: [Docs: Style Strings](https://starship.rs/advanced-config/#style-strings)), like:

```toml
[[battery.display]]
style = "italic mauve"
threshold=15

[[battery.display]]
style = "hidden"
threshold=90

[[battery.display]]
style = "italic mauve"
threshold=100
```
