### DISCUSSION TITLE
How to change/replace the default "❯" prompt symbol

### DISCUSSION THREAD

**Discussion by LittleHendrix** [starship/starship#5562] [Q&A] [answered]
Good day all,

I've been following the configuration documentation on the website, and tried adding the following to my `~/.config/starship.toml` file. 

```toml
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = " [λ](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = " [λ](bold red)"

```

the `add_newline` one works; however, the symbol remains to be default chevron. I'm not sure if there are additional settings needed for that to happen or not. Any help/suggestion would be much appreciated! 🙏 

Thank you!
