### DISCUSSION TITLE
How do I use a custom command within `cmd_duration`

### DISCUSSION THREAD

**Discussion by nbonfire** [starship/starship#5630] [Q&A]
I'd like my shell to announce when a long running command is done using MacOS "say" command. 

Here's an example custom command for this:

```toml
[custom.sayit] 
command = 'say hi'
style='bg:#9A348E'
symbol='[🔊](bg:#9A348E)'
when=true
ignore_timeout=true
```

I can get the custom command to work every time by adding it to my format string. Great! But I'd like to have it only fire when the cmd_duration calls for it, so I was expecting to be able to do something like this:

```toml
[cmd_duration]
style='bg:#9A348E'
format='''[${custom.sayit} $duration ]($style)'''
min_time=5000
show_notifications=true
min_time_to_notify=60000
```

the $duration shows up correctly in my prompt, but my custom command doesn't fire.  I'm using fish shell fwiw.
