### DISCUSSION TITLE
[Time] is in the next line

### DISCUSSION THREAD

**Discussion by sun2ot** [starship/starship#5688] [Q&A]
I have found the `$time`'s location in `format = '$all'`. But why is the time displayed on the second line when the time module is enabled?
I configure the time module like the example in docs:
```toml
[time]
disabled = false
format = '🕙[$time]($style)'
time_format = '%R'
```
And the result likes following:
```
yzh  in whr ~/.config via (conda symbol) base took 20s 
🕙11:45❯
```
