### DISCUSSION TITLE
How do I get the status of last command ($?) and display it in the prompt?

### DISCUSSION THREAD

**Discussion by squeaktoy** [starship/starship#5726] [Q&A] [answered]
Instead of a simple check or cross, I want to also display the status code the command returned. How can I do this?

**Comment by jankatins** [comment, marked as answer]
Enable the status module: https://starship.rs/config/#status and add any of the "number" variables  (e.g. status) to the format (this should be the default):

E.g. 
```toml
[status]
style = "bold red"
format = "[\\[$status\\]]($style) "
disabled = false
```
