### DISCUSSION TITLE
[Shell] Is that possible to disable shell indicator in the first-level shell?

### DISCUSSION THREAD

**Discussion by kirill-lappo-dg7** [starship/starship#5930] [Q&A]
I mostly work in bash, but sometimes I need to start pwsh right inside my bash session.

I enabled [shell] plugin, that shows type of current shell.

However, I need that only when I started a new shell inside of another. By default I work in bash and I don't need any indication for that.

For now I configured [shell] this way:

```toml
[shell]
bash_indicator = ''
format = '[$indicator]($style)'
disabled = false
style = 'cyan bold'
```

I had to remove space in the end of format string so `>` sign was not padded in bash.

I wonder are there any solutions other than emptying bash_indicator?
