### DISCUSSION TITLE
how to enable transient in zsh

### DISCUSSION THREAD

**Discussion by MushiTheMoshi** [starship/starship#5950] [Q&A]
hi there,

Awesome job done here!

Would like to know how can I enable transient prompt in my zsh session? could not find it in the documention...
I looked here: https://starship.rs/advanced-config/

Hope you can point me in the right direction...

Regards,
Julio

**Comment by DeadKper** [comment]
This is a bit late but here's how I made it "work", you need a bit more config to make it right, add this where you load starship
```zsh
eval "$(starship init zsh)"

TRANSIENT_PROMPT="${PROMPT// prompt / prompt --profile transient }"
TRANSIENT_RPROMPT="${PROMPT// prompt / prompt --profile rtransient }"

autoload -Uz add-zle-hook-widget
add-zle-hook-widget zle-line-finish transient-prompt

function transient-prompt() {
    PROMPT="$TRANSIENT_PROMPT" RPROMPT="$TRANSIENT_RPROMPT" zle .reset-prompt
}
```

and in starship.toml add 2 profiles, for the left and right prompt
```toml
format = "..."

[profiles]
transient="""
$character\
"""

rtransient="""
$status\
$cmd_duration\
$time\
"""
```

You can customize those profiles however you like, don't know if it works exactly how it should in every scenario but it has been working for me, time is a little off in the transient prompt though, haven't found a way to fix it

**Reply by DeadKper** [reply]
Update: Found a way to fix my issues with the transient prompt

This is the new zsh config:
```zsh
eval "$(starship init zsh)"

autoload -Uz add-zsh-hook
add-zsh-hook precmd transient-prompt-precmd

TRANSIENT_PROMPT="${PROMPT// prompt / prompt --profile transient }"
TRANSIENT_RPROMPT="${PROMPT// prompt / prompt --profile rtransient }"

function transient-prompt-precmd {
    # Fix ctrl+c behavior
    TRAPINT() { transient-prompt; return $(( 128 + $1 )) }

    # Save transient prompt
    SAVED_PROMPT="$(eval "printf '%s' \"${TRANSIENT_PROMPT}\"")"
    SAVED_RPROMPT="$(eval "printf '%s' \"${TRANSIENT_RPROMPT}\"")"
}

autoload -Uz add-zle-hook-widget
add-zle-hook-widget zle-line-finish transient-prompt

function transient-prompt() {
    # Use saved transient prompt
    PROMPT="$SAVED_PROMPT" RPROMPT="$SAVED_RPROMPT" zle .reset-prompt
}
```

**Comment by Praecthquil** [comment]
This method works but it disables the custom color palette I have set for the prompt, is there any way to remedy this? Also I'm not sure where most of the modules go. Do they go in the transient variable AND format variable like $character, or is it just $character in the transient variable?

**Reply by bric3** [reply]
Maybe the suggested tool in https://github.com/starship/starship/issues/888#issuecomment-3041226060 can help.

https://github.com/olets/zsh-transient-prompt gives customizable transient prompt abilities for any prompt.

**Reply by DeadKper** [reply]
This is my current config if you're interested, and this is how it looks:

<img width="2560" height="290" alt="image" src="https://github.com/user-attachments/assets/b25d0f00-73df-494b-8fe1-3e15494e8c74" />


~/.config/starship.toml
```toml
format = """
$shell\
$all\
$fill\
$container\
$status\
$cmd_duration\
$jobs\
$battery\
$time \
$line_break\
$character\
"""

command_timeout = 100
add_newline = false

[profiles]
transient="""
$character\
"""

rtransient="""
$status\
$cmd_duration\
$time\
"""

[status]
disabled = false

[line_break]
disabled = false

[fill]
disabled = false
symbol = " "

[character]
success_symbol = "[❯](bold #9134cc)"

[time]
disabled = false
style = "#909090"
format = "[$time]($style)"

[container]
symbol = ''
format = ' [$symbol \[$name\]]($style) '

[directory]
style = "bright-blue"
truncation_length = 10
truncate_to_repo = false
repo_root_style = "bold bright-blue"
read_only = " 󰌾"

[shell]
disabled = false

# the rest of the config is just for icons so I'll ignore that
# ...
```
