### DISCUSSION TITLE
Prompt breaks on resizing (invisible text)

### DISCUSSION THREAD

**Discussion by frolvanya** [starship/starship#6008] [Q&A]
As you can see, it works perfectly at the beginning of the video and then gets worse and worse, to the point where commands become invisible. I was using `powerline-rs` before and everything worked fine, so I guess it's not an issue of shell/terminal. Is it possible to fix it from config file (add some truncation or enable line break, I've checked docs but I didn't find anything related + I didn't find discussions with similar issues)?
 
https://github.com/starship/starship/assets/59515280/4ad7829d-c242-4bfe-bdc4-010411b7d941

System: macOS Sonoma 14.5
Terminal: Iterm2
Shell: fish
My config: 
```toml
"$schema" = "https://starship.rs/config-schema.json"

format = """
$time\
$directory\
$git_branch\
$git_status \
"""

[time]
disabled = false
time_format = "%H:%M"
style = 'fg:#3B4252 bg:#88C0D0'
format = '[](fg:#88C0D0)[$time]($style)[](fg:#88C0D0)'

[directory]
truncate_to_repo = false
truncation_symbol = "…/"
style = 'fg:#E5E9F0 bg:#3B4252'
format = "\b[ ](fg:#88C0D0 bg:#3B4252)[$path]($style)[](fg:#3B4252)"

[git_branch]
symbol = " "
style = "fg:#3B4252 bg:#8FBCBB"
format = "\b[ ](fg:#3B4252 bg:#8FBCBB)[$symbol$branch(:$remote_branch)]($style)[](fg:#8FBCBB)"

[git_status]
conflicted = " $count "
ahead = "⇡ $count "
behind = "⇣ $count "
diverged = "⇕ $count "
untracked = " $count "
stashed = " $count "
modified = " $count "
staged = " $count "
renamed = " $count "
deleted = " $count "
style = "fg:#E5E9F0 bg:#5E81AC"
format = "\b[ ](fg:#8FBCBB bg:#5E81AC)[$conflicted$ahead$behind$diverged$untracked$stashed$modified$staged$renamed$deleted]($style)[](fg:#5E81AC)"
```

P.S: I tried using `line_break`, but for some reason even with `break_below_width 60` it breaks always, so it's not a fix
