### DISCUSSION TITLE
How to remove trailing space if module is not in use?

### DISCUSSION THREAD

**Discussion by tembbo** [starship/starship#6077] [Q&A] [answered]
I have a python module like this
```toml
[python]
format = "[$virtualenv](yellow) "
```
and it works fine, if i enable my virtual env in a python project it shows the name, but if i run the command `deactivate` to deactivate the virtual environment, i get an extra space (most likely because of the trailing space in the starship.toml, but if i remove that, theres no seperation between the `❯` and the module)

activate the venv -> <img width="113" alt="Screenshot 2024-07-09 at 10 42 03 PM" src="https://github.com/starship/starship/assets/162893147/3b5d5673-7fa3-450b-97c1-babebebcb1b8">

deactivate the venv -> <img width="93" alt="Screenshot 2024-07-09 at 10 43 06 PM" src="https://github.com/starship/starship/assets/162893147/aa4f64bf-d2aa-4ee3-ac5c-a36a360c7dfd">
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎       ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎   ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎                      ^
   ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎   ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎                  extra space

**Comment by tembbo** [comment]
this is what i get when running `starship explain`

```
Here's a breakdown of your prompt:
 "❯ " (<1ms)           -  A character (usually an arrow) beside where the text is entered in your terminal
 "~/Dev/quiz " (<1ms)  -  The current working directory
 " " (<1ms)            -  The currently installed version of Python
```

and there you can see the empty python module, which should be disabled

**Comment by davidkna** [comment, marked as answer]
Please try this:
```toml
[python]
format = "([$virtualenv](yellow) )"
```

**Comment by tembbo** [comment]
That works! Thank you @davidkna! Could you please explain why that works.

I think im doing something similar with the git module, is that correct?

```toml
[git_status]
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted) ($ahead_behind )](red)"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
```
