### DISCUSSION TITLE
Powerline inspired prompt

### DISCUSSION THREAD

**Discussion by thesobercoder** [starship/starship#6138] [Show and tell] [answered]
Hi everyone,

Just wanted to showcase my latest powerline-inspired prompt, which I'm really proud of. I welcome any improvements or suggestions. Also, I'd appreciate guidance on reducing the duplication required to configure each language's styles. Is there a way to apply the styles across all languages?

![CleanShot 2024-07-29 at 23 54 29](https://github.com/user-attachments/assets/f717bf1a-fecf-44a5-8f84-36ab7d4e8fd8)

```toml
"$schema" = "https://starship.rs/config-schema.json"

format = """
[╭─](bold green)\
[](fg:#33658A)\
[$os](bg:#33658A)\
[](fg:#06969A bg:#33658A)\
[](fg:#86BBD8 bg:#06969A)\
$username$hostname\
[](fg:#86BBD8 bg:#D8BB86)\
$directory\
[](fg:#D8BB86 bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#FCF392)\
$golang\
$nodejs\
$bun\
$deno\
$rust\
$python\
$ruby\
$lua\
[](fg:#FCF392 bg:#7DF9AA)\
$package\
[](fg:#7DF9AA bg:#9A86D8)\
$aws\
$azure\
$gcloud\
$kubernetes\
[](fg:#9A86D8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[($shell)](bg:#33658A)\
[](fg:#33658A)\
[$line_break│](bold green)\
[$line_break╰─$character ](bold green)\
"""

continuation_prompt = "[╰─ ](bold green)"
command_timeout = 1000

[line_break]
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[os]
format = "[ $symbol]($style)"
style = "fg:#ffffff bg:#33658A"
disabled = false

[hostname]
ssh_only = true
style = "bg:#86BBD8 fg:#000000"
format = "[ $hostname ]($style)"

[username]
show_always = true
style_user = "bg:#86BBD8 fg:#000000"
style_root = "bold bg:#86BBD8 fg:#000000"
format = "[  ($user) ]($style)"

[directory]
style = "bg:#D8BB86 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
style = "bg:#FCA17D"
format = "[[ $symbol$branch ](fg:#000000 bg:#FCA17D)]($style)"
truncation_length = 20

[git_status]
style = "bg:#FCA17D"
format = "[[($all_status$ahead_behind )](fg:#000000 bg:#FCA17D)]($style)"

[shell]
disabled = false
style = "fg:#ffffff bg:#33658A"

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A"
format = "[[ 󰥔 $time ](fg:#ffffff bg:#33658A)]($style)"

[package]
style = "fg:#000000 bg:#7DF9AA"
format = "[ $symbol$version ]($style)"

[aws]
style = "bg:#9A86D8"
format = "[[ $symbol$profile ](fg:#000000 bg:#9A86D8)]($style)"

[azure]
disabled = false
style = "bg:#9A86D8"
format = "[[ $symbol$subscription ](fg:#000000 bg:#9A86D8)]($style)"

[gcloud]
style = "bg:#9A86D8"
format = "[[ $symbol$account ](fg:#000000 bg:#9A86D8)]($style)"

[kubernetes]
disabled = false
style = "bg:#9A86D8"
format = "[[ $symbol$context ](fg:#000000 bg:#9A86D8)]($style)"

[docker_context]
style = "bg:#06969A"
format = "[[ $symbol$context ](fg:#000000 bg:#06969A)]($style)"

[python]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"

[ruby]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"

[rust]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"

[golang]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"

[lua]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"

[bun]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"

[nodejs]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]

[deno]
style = "fg:#000000 bg:#FCF392"
format = "[ $symbol$version ]($style)"
```
