### DISCUSSION TITLE
Add backround color to time on right side

### DISCUSSION THREAD

**Discussion by pperesbr** [starship/starship#6283] [Q&A]
Hello, 

I'm started with starship and I'm customizing my prompt, I want to informations on left side and another informations on right side.

I set time on right side, but background color is not working. 

My configuration:

```toml
palette = "catppuccin_mocha"

format = """
[  ](bg:mauve fg:#090c0c)\
[](fg:mauve bg:green)\
$directory\
[ ](fg:green)\
"""

right_format = """

[](fg:pink)
$time\
"""

[directory]
style = "fg:mantle bg:green"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
style = "bold yellow"
format = "[ $time ](style=$style)"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

```

my actual status bar:

<img width="2998" alt="prompt" src="https://github.com/user-attachments/assets/4a74e384-81d3-4b31-89e8-aec8c032f4f9">

How to solve this?

Tks,

Paulo

**Comment by ghaaj** [comment]
this will do.
```toml
[time]
style = "bold fg:yellow bg:pink"
format = "[ $time ]($style)"
disabled = false
```
