### DISCUSSION TITLE
Specific status symbols not showing?

### DISCUSSION THREAD

**Discussion by ShaiAvr** [starship/starship#6286] [Q&A]
According to the [docs](https://starship.rs/config/#status), by default the status module has different symbols for different types of errors such as "command not found" and Ctrl+C. However, after enabling this module and configuring its format, I only get the general error symbol no matter what type of error it is. the `$common_meaning` variable does show me a message such as "NOTFOUND", so it should know to display the not-found symbol, but it doesn't:

![Screenshot 2024-09-29 181404](https://github.com/user-attachments/assets/408fb249-04d6-4804-8a20-29d175719802)
Why doesn't it show the specialized symbols for "command not found", "Ctrl+C" and "file not executable"?
The relevant part of my `starship.toml`:
```toml
[status]
disabled = false
format = '\[[$symbol $status( $common_meaning)( Signal: $signal_number $signal_name)]($style)\] '
```
I am using Windows 11 with WSL 2 running Ubuntu 24.04 if it helps.
