### DISCUSSION TITLE
How to correctly apply changes of config?

### DISCUSSION THREAD

**Discussion by sharpchen** [starship/starship#6299] [Q&A]
It doesn't apply my changes even after I entered a new session. What do I do?

With the following config, prompt is still default

```toml
[dotnet]
symbol = " "
format = '[$symbol($version )($tfm)]($style)'
```

![image](https://github.com/user-attachments/assets/2df625ee-4bea-43cd-b477-ccc1535425bc)
