### DISCUSSION TITLE
character module in same line as the rest of modules

### DISCUSSION THREAD

**Discussion by Masber** [starship/starship#6365] [Q&A] [answered]
dear starship community,

I would like to know if it is possible to put the symbol in the character module in same line as the rest of modules. This is the only way I could achieve this

```toml
add_newline = false

[character]
format = "$all"
```

![image](https://github.com/user-attachments/assets/179278cd-2e16-4917-b949-bda365103480)

If I add a character to format, then that character goes to next line

```toml
add_newline = false

[character]
format = "$all > "
```

![image](https://github.com/user-attachments/assets/e1cc3ed1-1561-407d-97db-65f1329324de)

I would like the prompt to be one single line (including character module) like:

> manta on  main [!] is 📦 v1.53.10 via 🦀 v1.82.0 >

Is this possible?

thank you
