### DISCUSSION TITLE
Conda environment on top of the left prompt

### DISCUSSION THREAD

**Discussion by FahimAnayet** [starship/starship#6418] [Q&A]
![Screenshot 2024-11-28 at 4 10 52 PM](https://github.com/user-attachments/assets/63192483-c913-4af9-b6b2-f19cdbab7b52)
How can I remove that conda env name in the left side `[py11]` This is my starship config. Using nu shell. Tried with zsh, it's same.
And why it's three line! How can I use two line prompt. right prompt should be aligned with the main prompt. Where did I go wrong?
```
starship 1.20.1
branch:master
commit_hash:f505324
build_time:2024-07-27 09:09:15 +00:00
build_env:rustc 1.80.0 (051478957 2024-07-21),stable-aarch64-apple-darwin
```
```toml
add_newline = true
palette = 'myCustom'
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
[ ](fg:#a3acd0)\
$directory\
$git_branch\
$git_status\
$fill
$character"""

right_format = """
$python\
$conda\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$line_break\
$cmd_duration"""

[directory]
home_symbol = ' ~'
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '󰝰 …/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '
fish_style_pwd_dir_length = '2'

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[ ](cyan) [$symbol$branch ]($style)'

[git_status]
style = "cyan"
format = '([$all_status$ahead_behind]($style) )'
conflicted = '=${count}'
ahead = '[⇡$count ](green)'
behind = '[⇣$count ](red)'
diverged = '⇕${count}'
up_to_date = '${count}'
untracked = '[?$count ](blue)'
stashed = '$${count}'
modified = '[!$count ](yellow)'
staged = '+${count}'
renamed = '»${count}'
deleted = '[✘$count ](orange)'

[git_state]
style = "black"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray1'
format = ' [$duration]($style)'

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
gray1='#828997'
black = '#2E3440'
white='#D8DEE9'

[palettes.onedark]
dark_blue='#61afef'
blue='#56b6c2'
red='#e06c75'
green='#98c379'
purple='#c678dd'
cyan='#56b6c2'
orange='#be5046'
yellow='#e5c07b'
gray='#828997'
white ='#abb2bf'
black='#2c323c'


[palettes.myCustom]
dark_blue='#61afef'
blue='#3BA4ED'
red='#e05f30'
green='#65D837'
purple='#c678dd'
cyan='#56b6c2'
orange='#be5046'
yellow='#e5c07b'
gray='#828997'
white ='#abb2bf'
black='#2c323c'
```
Thank you 😄
