### DISCUSSION TITLE
Is it possible to have a dynamic random character for the Character module?

### DISCUSSION THREAD

**Discussion by azzamsa** [starship/starship#6428] [Q&A]
Hi,

Currently, I am using this config:

```toml
[character]
success_symbol = '[🦄](bold green)'
error_symbol = '[🙊](bold red)'
```

Is there any way to have a random character for `succes_symbol`?
Something like:

```toml
[character]
format = "[$symbol $output]($style)"
symbol = "$(~/emojis.sh)"
style = "bold yellow"
```

```bash
#!/bin/bash
emojis=("🙂" "😎" "🌟" "🔥" "✨" "🚀" "🌈" "💡")
count=${#emojis[@]}
index=$((RANDOM % count))
echo -n "${emojis[$index]}"
```

So I can get random emoji each time the prompt is drawn.

Thanks! 🍩
