### DISCUSSION TITLE
Background color issue with right-side icons in terminal

### DISCUSSION THREAD

**Discussion by mortymacs** [starship/starship#6451] [Q&A]
Hi,

In the Neovim terminal, I always encounter this problem where the right-side icons don't display the correct background color. However, outside of Nvim, everything works fine.
![image](https://github.com/user-attachments/assets/a54add73-6752-4568-86ba-7ae517dfcd7e)
(The top one is outside Nvim, and the bottom one is inside of Nvim)
It's not a Neovim problem.
I tried to figure it out and I found something that might help. When I use `right_format`, it solves the issue, but the problem is it shows the right side on the next line as I have `$line_break` in my `format`. Alternatively, if I stop using `$character`, it works, but that's not useful because I need the character.

This is the structure I'm looking for:
![image](https://github.com/user-attachments/assets/152c9b15-c0a6-4b51-b619-a80aca83307d)
which I was able to achieve. Here is the config:
```toml
format = "$sudo
$username
(bg:#633359 fg:#2e294e)
$directory
(bg:#973c64 fg:#633359)
$git_branch
$git_commit
$git_state
$git_metrics
(fg:#973c64 bg:#0E131F)
$fill
(bg:#0E131F fg:#ed4a4a)
$nix_shell
(bg:#ed4a4a fg:#33465b)
$status
(bg:#33465b fg:#5b3758)
$cmd_duration
(bg:#5b3758 fg:#44355b)
$jobs
(bg:#44355b fg:#973c64)
$git_status
$line_break
$character"
```
but only inside editors I have that problem.
Any idea how to achieve the same output (as expected structure) by using the `right_format` or any other alternative solutions to address the issue?

Thanks!

**Comment by mortymacs** [comment]
I prepared a very simple config to reproduce the issue with `right_format`.
Here I could fix the background color issue by using `right_format`, but the problem is that the prompt is still on the same line while I need it to be on the next line:
```toml
format = "$username(bg:#633359 fg:#2e294e)$directory(bg:#973c64 fg:#633359)"
right_format = "$status(bg:#33465b fg:#5b3758)"

[status]
disabled = false
format = "[ $status ]($style)"
style = "bold bg:#33465b fg:#f5e2c8"
```

![image](https://github.com/user-attachments/assets/0acfc7e3-db76-4116-9483-69cd64223a75)
