### DISCUSSION TITLE
The right most prompt char is cut off in fish but not zsh

### DISCUSSION THREAD

**Discussion by ningw42** [starship/starship#6468] [Q&A]
Not sure if there is something wrong in my configuration (fish or starship, attached at the bottom). This is what I get from a ssh session in various terminal emulators. The right most module (in my case, time) has the right most char cut off. 

![image](https://github.com/user-attachments/assets/a0efd12a-420e-4c47-a2cc-860fde3d2e50)

Here is what in text

```shell
~ ································································································································································   ning@yuki   12:00:26
❯ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

~ ································································································································································   ning@yuki   12:00:3
❯
```

I tried the below:
1. Login shell `zsh`, `$SHLVL` is 1, works fine.
2. Launch `fish` from `zsh`, `$SHLVL` is 2, the right most char is cut off.
3. Launch `zsh` from `zsh`, `$SHLVL` is 2, works fine.
4. Launch nix-shell with `--command zsh`, `$SHLVL` is 3 (nix-shell uses bash to bootstrap everything, so it's zsh/bash/zsh), works fine.
5. Launch nix-shell with `--command fish`, `$SHLVL` is 3 (zsh/bash/fish), the same cutoff.
6. Append a different module `hostname` to the right most, the same cutoff happens in `fish` but not `zsh`.
7. All the same in Windows Terminal and WezTerm.

As long as the final shell is `fish`, starship's prompt has its right most char cut off.

![image](https://github.com/user-attachments/assets/39f5ea6c-56e3-4899-bb9d-126a31ba175a)
```shell
~/g/nixfiles   master !2 ·····························································································································   8s   ning@yuki   12:05:17@yuki
❯ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

~/g/nixfiles   master !2 ···································································································································   ning@yuki   12:05:38@yuk
❯
```

Here is my `starship.toml`
```toml
"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
$git_status\
$nix_shell\
$fill\
$cmd_duration\
$os\
$username\
$hostname\
$time\
$line_break\
$character\
"""

palette = "gruvbox_dark"

[palettes.gruvbox_dark]
fg = "#ebdbb2" # alias of fg1
fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984"
bg = "#282828" # alias of bg0
bg0_soft = "#32302f"
bg0_hard = "#1d2021"
bg0 = "#282828"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
purple = "#b16286"
aqua = "#689d6a"
orange = "#d65d0e"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_purple = "#d3879b"
bright_aqua = "#8ec07c"
bright_orange = "#fe8019"

# modules to the left, remember to add an extra space to the right of them.
[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
read_only = " " # an extra space is appended because it would always has a space if we do it in directory.format
style = "fg:bright_blue"
read_only_style = "fg:bright_yellow"
truncation_length = 3
truncation_symbol = ".../"
use_os_path_sep = true # OS specific path separator. e.g. "\" for Windows
fish_style_pwd_dir_length = 1 # "~/Dev/Nix/nixpkgs/pkgs" will be "~/D/N/nixpkgs/pkgs" instead of "nixpkgs/pkgs"

[git_branch]
symbol = ""
style = "fg:bright_green"
format = "[$symbol  $branch ]($style)"

[git_status]
format = "($ahead_behind )($all_status )" # parentheses make them conditional strings, so that we won't end up with an extra space
# branch status ($ahead_behind)
ahead = "[⇡${count}](fg:bright_green)"
behind = "[⇣${count}](fg:bright_red)"
diverged = "[⇡${ahead_count}](fg:bright_green)[⇣${behind_count}](fg:bright_red)"
up_to_date = ""
# file status ($all_status)
conflicted = "[=${count}](fg:yellow)"
untracked = "[?${count}](fg:yellow)"
stashed = "[\\$${count}](fg:yellow)" # "$" has to be excaped by "\$", so it becomes "\\$" in literal. the output would be "$3" if there are 3 stashes.
modified = "[!${count}](fg:yellow)"
staged = "[+${count}](fg:green)"
renamed = "[»${count}](fg:yellow)"
deleted = "[✘${count}](fg:red)"

[nix_shell]
format = "[$symbol  $state\\($name\\) ]($style)" # "(" has to be escaped by "\(", so it becomes "\\(" in literal.
symbol = ""
style = "fg:bright_blue"


# module that conencts the left part and the right part
[fill]
symbol = "·"
style = "fg:bg1"


# modules to the right, remember to add an extra space to the left of them.
# status of the previous command, not enabled in global format because it hasn't been configured properly
[status]
disabled = false
format = " [$symbol$status]($style)"
symbol = "❌"
success_symbol = ""
not_executable_symbol = ""
not_found_symbol = "🔍"
sigint_symbol = ""
signal_symbol = ""

[cmd_duration]
min_time = 5000 # 5s
format = "[   $duration]($style)"
style = "fg:yellow"

[os]
style = "fg:fg3"
format = "[ $symbol]($style)"
disabled = false

# just the OSs I use
[os.symbols]
Windows = "󰍲 "
Macos = "󰀵 "
NixOS = " "

[username]
show_always = true
style_user = "fg:fg3"
style_root = "fg:bright_red"
format = "[ $user]($style)"

[hostname]
ssh_only = false
style = "fg:fg3"
format = "[@$hostname]($style)"

[time]
disabled = false
time_format = "%T"
style = "fg:blue"
format = "[   $time]($style)"


# second line
[line_break]
disabled = false

# not enabled in global format
[shell]
disabled = false

[character]
disabled = false
success_symbol = "[❯](bold fg:bright_green)"
error_symbol = "[❯](bold fg:bright_red)"
vimcmd_symbol = "[❮](bold fg:bright_green)"
vimcmd_replace_one_symbol = "[❮](bold fg:bright_purple)"
vimcmd_replace_symbol = "[❮](bold fg:bright_purple)"
vimcmd_visual_symbol = "[❮](bold fg:bright_yellow)"
```

And very simple `config.fish` managed by `home-manager`
```fish
# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/wwjnbimfivkh9wkxcrl1dd594yw9w65g-hm-session-vars.fish



status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias ip 'ip --color=auto'
    alias l 'eza --group-directories-first --icons --long --group --header --time-style=iso --binary --all'
    alias ll 'eza --group-directories-first --icons --long --group --header --accessed --modified --created --time-style=iso --binary --all'
    alias llt 'eza --group-directories-first --icons --long --group --header --accessed --modified --created --time-style=iso --binary --tree'
    alias lt 'eza --group-directories-first --icons --long --group --header --time-style=iso --binary --tree'
    alias vimdiff 'nvim -d'
    alias zj zellij

    # Interactive shell initialisation
    /nix/store/qb76l3bdjlld3xdvr2clbqwsi8l1rh5j-fzf-0.57.0/bin/fzf --fish | source

    # configure gruvbox theme
    theme_gruvbox dark medium

    set -gx GPG_TTY (tty)

    /nix/store/l4k3n4vi2y5qjzzhihr37jwhwxz4vxdq-zoxide-0.9.6/bin/zoxide init fish | source

    if test "$TERM" != dumb
        /home/ning/.nix-profile/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/ning/.local/share/fish/home-manager_generated_completions" $post
    end


end
```
