### DISCUSSION TITLE
Automatically update git status in prompt for tracked remote branches

### DISCUSSION THREAD

**Discussion by wigging** [starship/starship#6503] [Q&A]
When I `cd` to a Git repository on my local computer, I have to manually run `git fetch` for the `git_status` in the prompt to update. Is there a way I can have the Starship prompt automatically update the `git_status` without me having to run `git fetch` first? This would be very useful for the times when I forget to pull down the latest remote changes; because the prompt would automatically show me if changes were made on the remote.

I'm running zsh on macOS. Here is my `starship.toml` config file:
```toml
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$conda\
$character"""

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "≠"
untracked = "*"
modified = "*"
renamed = "*"
ahead = "\uf062"
behind = "\uf063"
diverged = "\uf063 \uf062"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[($virtualenv )]($style)"
style = "bright-black"

[conda]
format = "[($environment )]($style)"
style = "bright-black"

```
