### DISCUSSION TITLE
How to Adjust (reorder) the Position of a Context Module in the Starship Prompt?

### DISCUSSION THREAD

**Discussion by pyxelr** [starship/starship#6512] [Q&A] [answered]
Hi,

I have added a [kubernetes](https://starship.rs/config/#kubernetes) context to my `starship.toml` configuration:

```toml
[kubernetes]
format = '[☸ $context](dimmed green) '
disabled = false
```

Currently, the Kubernetes context appears at the very beginning of the Starship prompt, just before the path:

![2025-01-22 at 12 20 58](https://github.com/user-attachments/assets/807534ed-2ed0-4adf-b928-950935e423af)

I would like to move the Kubernetes context to a different position in the prompt, for example, after the AWS region module. How can I achieve this?
