### DISCUSSION TITLE
How to display the full path with the full directory (`/home/user01`) instead of the tilde (`~`)

### DISCUSSION THREAD

**Discussion by bjce** [starship/starship#6529] [General]
Hello. First of all many thanks to the maintainers of starship. I would like to know how can I edit the `.config/starship.toml` file to display the full path with the full directory (`/home/user01`) instead of the tilde (`~`)?

**Comment by ankddev** [comment]
I found two solutions.
1. Set `directory.home_symbol` to your home directory path like this:
```toml
# .config/starship.toml
[directory]
home_symbol = "/home/user01"
```
For Windows you can use it like this:
```toml
# .config/starship.toml
[directory]
# Use \\ instead \ because we need to escape it
home_symbol = "C:\\Users\\user"
```
This will change your home path icon in prompt to full path.
2. Set `directory.substitutions
```toml
# .config/starship.toml
[directory.substitutions]
'~' = '/home/user01'
```
And for Windows:
```toml
# .config/starship.toml
[directory.substitutions]
'~' = 'C:\Users\user'
```
And this will replace `~` text in path with full path of home directory.
