### DISCUSSION TITLE
Git username

### DISCUSSION THREAD

**Discussion by jc211** [starship/starship#6540] [Q&A]
Hi, thank you for the amazing work! Is there a way to display the git username?

**Comment by davidkna** [comment]
Please try this:
```toml
[custom.git_user]
when = true
require_repo = true
use_stdin = false

shell = ["git", "config"]
command = "user.name"
```
