### DISCUSSION TITLE
Home symbol and current directory styling

### DISCUSSION THREAD

**Discussion by pedrocarlo** [starship/starship#6592] [Q&A]
How can we customize the styling for the home symbol and the current directory? Is it only possible with custom commands?

This is what I currently have with p10k with lean style:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/b895741d-c2cf-4567-9e02-62a7e826432b" />

This is the configuration I have currently with starship, but without the things I mentioned above:

```toml
format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$username\
$hostname\
$time\
$line_break\
$character
"""

[directory]
before_repo_root_style = 'dimmed 39'
format = "[╭─ ](238)[$path]($style) "
repo_root_format = "[╭─ ](238)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($before_repo_root_style) "
repo_root_style = '39 bold'
style = "39 bold"
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[$symbol]($style)[$branch](76)[(:$remote_branch)]($style) "
symbol = ""

[git_status]
ahead = '[($count](green)'
behind = '[($count](green)'
deleted = '[$count](red) '
format = '([$all_status$aheadbehind]($style) )'
modified = '[!$count](178) '
staged = '[+$count](178) '
stashed = '[*$count](76) '
untracked = '[?$count](75) '

[cmd_duration]
format = "[$duration]($style) "
min_time = 0
style = "101"

[fill]
symbol = " "

[username]
format = "[$user@]($style)"
show_always = true
style_user = "180"

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
style = "180"

[time]
disabled = false
format = "[$time]($style) "
style = "66"

[character]
error_symbol = "[❯](196)"
format = "[╰─](238)$symbol "
success_symbol = "[❯](76)"
```
