### DISCUSSION TITLE
How to disable project version display?

### DISCUSSION THREAD

**Discussion by TajangSec** [starship/starship#6641] [Q&A] [answered]
I don't want to display this version shown in the image, how can I turn it all off?
![Clip_2025-03-20_16-45-08](https://github.com/user-attachments/assets/ccfcc293-e035-461c-8119-e5a64613754d)

**Comment by TajangSec** [comment, marked as answer]
I solved it, although the implementation was a bit silly. I set `disabled = true` for each item
```toml
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[directory]
disabled = false
format = "[$path]($style)[$read_only]($read_only_style)\n"
style = 'bold cyan'
read_only = '🔒'
read_only_style = 'red'
use_os_path_sep = true

[package]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[nodejs]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fill]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[gleam]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = true

[localip]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[hg_branch]
disabled = true

[mojo]
disabled = true

[nats]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[odin]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true

```
